### ISSUE TITLE
helm cluster模式启动后，报错

### ISSUE THREAD

**Issue by rim-wood** [nacos-group/nacos-k8s#100]
lookup nacos-hs on 10.43.0.10:53: no such host

**Comment by paderlol** [comment]
麻烦描述错误的时候详细点，你这个信息我没法分析

**Comment by paderlol** [comment]
自己重新pull一下模板试下,这个模板没有添加tolerate-unready-endpoints注解

**Comment by rim-wood** [comment]
nacos-hs和nacos-cs两个service都启动了，但nacos的StatefulSet启动不起来，用kubectl logs -f --tail 100 nacos-0 -n nacos查看日志，显示lookup nacos-hs on 10.43.0.10:53: no such host

**Comment by paderlol** [comment]
你自己独立使用的命名空间？

**Comment by paderlol** [comment]
你有没有重新pull工程 我刚刚重新加了tolerate-unready-endpoints注解在模板里面

**Comment by rim-wood** [comment]
pull 了，但是我开了health检测
![image](https://user-images.githubusercontent.com/13330165/75655535-0adb8180-5c9d-11ea-9356-66e7f531f7cf.png)

**Comment by rim-wood** [comment]
名称空间新建了的，都在同一个名称空间下，pvc-pc都没有问题，就是nacos的pod起不来

**Comment by rim-wood** [comment]
关闭health检测可以启动了，哈哈，黑人问号？？？

**Comment by paderlol** [comment]
那个health是有问题的,我在deployment里面去掉了,helm没有移除 我现在移除下

**Comment by rim-wood** [comment]
还有个小问题，这个地方
![image](https://user-images.githubusercontent.com/13330165/75657323-ea152b00-5ca0-11ea-9fed-5513dc2c78e0.png)

**Comment by paderlol** [comment]
好的 谢谢

**Comment by WeberMu** [comment]
spec:
  publishNotReadyAddresses: true

headless service添加这个参数试下

**Comment by Zhang21** [comment]
What do I do if domain names of headless Services cannot be resolved after I update CoreDNS?
Issue
Earlier versions of open source components, such as etcd, Nacos, and Kafka, cannot work as normal if Kubernetes 1.20 or later and CoreDNS 1.8.4 or later are used.

Causes
CoreDNS 1.8.4 or later preferably uses the EndpointSlice API to synchronize the IP addresses of the Services in your cluster. Some open source components will use the service.alpha.kubernetes.io/tolerate-unready-endpoints annotation provided by the Endpoint API to release Services that are not ready during the initialization phase. The annotation is deprecated in the EndpointSlice API and replaced with publishNotReadyAddresses. Therefore, you cannot release Services that are not ready after you update CoreDNS. As a result, the open source components cannot perform service discovery.

Solutions
Check whether the YAML file or Helm chart of the open source component contains the service.alpha.kubernetes.io/tolerate-unready-endpoints annotation. If yes, the open source component cannot work as expected. You need to update the component or consult the open source community.

**Comment by Zhang21** [comment]
https://www.alibabacloud.com/help/en/ack/ack-managed-and-ack-dedicated/user-guide/dns-troubleshooting-1

**Comment by Zhang21** [comment]
是由于 coreDns 版本的问题，按照上面文档，修改 nacos-hs headless svc 的 annotations:

```yml
# coredns 1.8.4之前的版本
annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

# coredns 1.8.4 之后的版本
  annotations:
    service.alpha.kubernetes.io/publishNotReadyAddresses: "true"
```
