### ISSUE TITLE
nacos控制台不能登录

### ISSUE THREAD

**Issue by hellomyheart** [nacos-group/nacos-k8s#102]
我之前的nacos是部署在k8s上的.
今天启动之后发现naocos一直在初始化，好像是在下载新版本，更新完之后服务注册发现都没有问题.但是登录nacos控制台时登录页面一闪而逝，并弹出"Request error, please try again later!"这个提示.
我的登录网址是k8s-master结点IP/nacos/#/login,是nacos的登录地址改变了吗？

**Comment by paderlol** [comment]
清理下缓存和localstorage.似乎是前端页面有问题，现在前端的小伙伴已经在处理了，试一下/nacos/index.html#login去登录.

**Comment by paderlol** [comment]
你先尝试下，不行，我就把latest回滚到1.1.4版本了

**Comment by hellomyheart** [comment]
已经可以了,清理了浏览器缓存就行了

**Comment by hellomyheart** [comment]
感谢！

**Comment by paderlol** [comment]
暂时不要使用右上角的修改密码，那个有问题，正在修复

**Comment by paderlol** [comment]
可以的话，麻烦点个star就好😄
