### ISSUE TITLE
k8s 部署后报错 Have not found myself in list yet

### ISSUE THREAD

**Issue by Cassuis** [nacos-group/nacos-k8s#103]
2020/03/11 18:01:27 Have not found myself in list yet.
My Hostname: nacos-1.nacos-headless.nacos.svc.cluster.local
Hosts in list: nacos-0.nacos-headless.nacos.svc.cluster.local

**Comment by Cassuis** [comment]
2020-03-11 18:05:42,979 INFO receive config info: unknown#nacos-1.nacos-headless.nacos.svc.cluster.local:8848#1583921142979#1

**Comment by paderlol** [comment]
你用的什么方式部署的？还有k8s版本多少？

**Comment by Cassuis** [comment]
> 你用的什么方式部署的？还有k8s版本多少？

k8s版本是v1.17.3
部署方式是StatefulSet

**Comment by paderlol** [comment]
看一下wiki里面的关于插件使用的问题，可能是unready point已经被删除了，你需要改成新

**Comment by Cassuis** [comment]
> 看一下wiki里面的关于插件使用的问题，可能是unready point已经被删除了，你需要改成新

可以给个链接吗，抱歉。没找到在哪里看。。。

**Comment by paderlol** [comment]
https://github.com/nacos-group/nacos-k8s/wiki/%E4%BD%BF%E7%94%A8peerfinder%E6%89%A9%E5%AE%B9%E6%8F%92%E4%BB%B6

**Comment by Cassuis** [comment]
> https://github.com/nacos-group/nacos-k8s/wiki/%E4%BD%BF%E7%94%A8peerfinder%E6%89%A9%E5%AE%B9%E6%8F%92%E4%BB%B6

改成了 publishNotReadyAddresses: true 
还是一样的错误日志
2020/03/11 20:28:42 Have not found myself in list yet.
My Hostname: nacos-0.nacos-headless.nacos.svc.cluster.local
Hosts in list: nacos-0.nacos-headless.nacos.svc.cluster.local

**Comment by paderlol** [comment]
等等 你pod启动成功了吗？

**Comment by paderlol** [comment]
这个日志不一定是代表错误,如果你的列表已经包含这个节点域名 也会出现这个日志的,你关注你的pod启动成功没 nacos的日志

**Comment by Cassuis** [comment]
> 这个日志不一定是代表错误,如果你的列表已经包含这个节点域名 也会出现这个日志的,你关注你的pod启动成功没 nacos的日志

pod启动成功了的。只是不能nodeport所以在想如何对外暴露端口

**Comment by Cassuis** [comment]
> > 这个日志不一定是代表错误,如果你的列表已经包含这个节点域名 也会出现这个日志的,你关注你的pod启动成功没 nacos的日志
> 
> pod启动成功了的。只是不能nodeport所以在想如何对外暴露端口

而且我看日志是一秒刷一条，这样产生日质量有点大。

**Comment by paderlol** [comment]
至于如何放端口建议去官方参考ingress如何使用？日志量大，这个是插件打印的，并不是nacos，这个peerfinder插件是我用go重新写的，我只是做个例子证明nacos自动扩容，生产建议不要使用.

**Comment by Cassuis** [comment]
> 至于如何放端口建议去官方参考ingress如何使用？日志量大，这个是插件打印的，并不是nacos，这个peerfinder插件是我用go重新写的，我只是做个例子证明nacos自动扩容，生产建议不要使用.

好的，谢谢帮助，祝你们越来越棒。

**Comment by Cassuis** [comment]
> > 至于如何放端口建议去官方参考ingress如何使用？日志量大，这个是插件打印的，并不是nacos，这个peerfinder插件是我用go重新写的，我只是做个例子证明nacos自动扩容，生产建议不要使用.
> 
> 好的，谢谢帮助，祝你们越来越棒。

另外mysql的dockerfile是开源的吗？想参考下

**Comment by paderlol** [comment]
那个没开源，因为只是简单封装了下脚本初始化，没啥东西的
