### ISSUE TITLE
没有 1.1.4 版本对应的 部署 nacos yml

### ISSUE THREAD

**Issue by WywTed** [nacos-group/nacos-k8s#105]
在 项目 nacos-docker 中， 1.1.4 分支中，application.properties 中使用的 数据库环境变量名和 nacos-k8s 中没有匹配的
![image](https://user-images.githubusercontent.com/12699301/76873807-37041e80-68a9-11ea-85bc-6c36703a86da.png)

**Comment by WywTed** [comment]
在 nacos-k8s 中没有与 nacos-docker 对应的分支；

**Comment by paderlol** [comment]
哦，知道了，请参考nacos docker的readme，从1.1.4的版本后续已经移除了主从数据库配置，只支持单个数据库，因为主从数据库的配置是有问题的，具体参考README.有专门的说明，k8s这边的例子已经完全移除了，你可以选择升级docker版本

**Comment by paderlol** [comment]
如果一定需要使用nacos docker 1.1.4的镜像那么k8s例子的关于数据库的环境变量可能需要自己去做了

**Comment by willinwu** [comment]
既然开发一直跟着nacos走，这边的tag也应该跟着那边走才合理。
这不是没有tag的理由，而且从0.4-1.2之间一直没有tag。

**Comment by paderlol** [comment]
这个本就是给大家借鉴的例子，所以之前不会考虑做tag，而且那种主从模式我在变更的时候做了wiki说明，如果保留下来是会出问题的。

**Comment by paderlol** [comment]
@willinwu 我已经打了1.1.4的tag上来了,不过我还是强烈建议你们不要按照1.1.4的k8s去部署,即使去使用也请去掉主从部署数据库的方式,因为这个确实是我前期设计导致的问题,后面有类似的重大改造,导致例子不兼容的情况,我会使用tag去记录下来,不过一般情况还是会直接使用master.还是谢谢你们提的意见
