### ISSUE TITLE
peer-finder plugin's souce code

### ISSUE THREAD

**Issue by WywTed** [nacos-group/nacos-k8s#106]
Hi, where can i see the souce code about peer-finder plugin.

**Comment by paderlol** [comment]
你如果需要最早版的源码可以去k8s的的实验项目去看，是用go语言写的，我只是拿过来稍微改了下，所以就不贴源码了

**Comment by WywTed** [comment]
![image](https://user-images.githubusercontent.com/12699301/77030998-4d11fc00-69db-11ea-86a7-7d5277a26e03.png)
按照文档部署后， 日志一直是这样的；

**Comment by paderlol** [comment]
这个是插件的日志warn日志，不影响使用，我等下去掉了重新发一个镜像吧

**Comment by paderlol** [comment]
这个问题已经修复了,你重新拉取下peer-finder插件镜像就好了,还有如果你想看源码可以去这里,这是K8S的一个实验项目,https://github.com/kubernetes-retired/contrib/tree/master/peer-finder

**Comment by WywTed** [comment]
@paderlol  可以提供这个插件的源代码吗， 准备构建 arm64 架构下的镜像，需要重新编译 二进制文件；
