### ISSUE TITLE
nacos-k8s 可以不用MYSQL么

### ISSUE THREAD

**Issue by sunney2010** [nacos-group/nacos-k8s#107]
nacos-k8s 只用于本地测试，不用MYSQL版本。mysql还有主备库，对于本地来说太重了。需要能测试则可以。谢谢

**Comment by paderlol** [comment]
已经去掉主从数据库了啊，但是不用数据库只能启动单机，但是单机在k8s上面对nacos的注册中心会有数据丢失风险，所以建议还是启动数据库

**Comment by liangyuanpeng** [comment]
去掉了从数据库可以考虑启动一个单机NACOS+单机数据库

**Comment by fency12** [comment]
请问不在k8s上新建mysql、nfs怎么使用？这文档写的也太草了，高级使用，只有部署mysql、nfs后才能部署nacos。我们有阿里云的rd、nfs不想搭建了，直接用怎么配？

**Comment by paderlol** [comment]
现在已经支持单机数据库
