### ISSUE TITLE
能否增加openshift的部署

### ISSUE THREAD

**Issue by Bryce-huang** [nacos-group/nacos-k8s#109]

**Comment by paderlol** [comment]
嗯，不好意思，我没用过openshift去部署过，所以暂时不会有，如果你用过可以提供一个例子pr进来的。

**Comment by paderlol** [comment]
嗯，不好意思，我没用过openshift去部署过，所以暂时不会有，如果你用过可以提供一个例子pr进来的。

**Comment by kinkocho** [comment]
@Bryce-huang 请问你这边最后实现了openshift上的集群部署了吗 我们这边也有类似问题😅

**Comment by kinkocho** [comment]
@paderlol 在openshift上面通过peer-finder 提示无法解析DNS。 我查了下资料是因为需要service为headless类型的。 在openshift的pod定义文件里面貌似不支持这个字段。。 不知道有没有其他方式可以动态获取

**Comment by paderlol** [comment]
不好意思，我之前没有搞过openshfit部署这块

**Comment by kinkocho** [comment]
@paderlol 大神有没有考虑集成下啊。 openshift上面部署的需求以后应该会越来越多吧

**Comment by paderlol** [comment]
我有时间试着学习下😅

**Comment by Bryce-huang** [comment]
https://github.com/nacos-group/nacos-k8s/pull/129

> @Bryce-huang 请问你这边最后实现了openshift上的集群部署了吗 我们这边也有类似问题😅

我已经提了pr了，参考https://github.com/nacos-group/nacos-k8s/pull/129

**Comment by kinkocho** [comment]
@Bryce-huang 非常感谢

**Comment by xiqning** [comment]
@Bryce-huang 按照template中的内容，docker pull openshift/origin-oauth-proxy:4.5.0镜像，没有找到该镜像。请问这个镜像在哪个具体的镜像库中？

**Comment by paderlol** [comment]
openshift/oauth-proxy，你试下这个看看？

**Comment by Bryce-huang** [comment]
it solved.
