### ISSUE TITLE
本地服务器部署在k8s，怎么暴露从局域网访问到管理界面

### ISSUE THREAD

**Issue by Jackjun724** [nacos-group/nacos-k8s#112]
本地服务器部署在k8s，怎么暴露从局域网访问到管理界面，clusterIP:none ，没办法修改type为nodeport

**Comment by paderlol** [comment]
两个方案，一 移除插件，你就可以使用nodeport ，或者其他的，但是ip自己配置，参考quickstart的做法，第二个，请去查看ingress相关用法

**Comment by Jackjun724** [comment]
谢谢 已在ingress分支找到解决办法
