### ISSUE TITLE
k8s部署nacos必须用分布式存储吗？

### ISSUE THREAD

**Issue by letcodeff** [nacos-group/nacos-k8s#114]
请问k8s部署nacos必须用分布式存储吗？用local-path也可以吧？只要保证nacos节点不全部挂掉就可以吧？或者用label标签指定机器也可以吧？

**Comment by paderlol** [comment]
里面的raft data数据如果你能保持重启pvc不漂移也可以，包括机器扩容缩容

**Comment by liangyuanpeng** [comment]
这个取决于业务的情况，和nacos没有必然联系。只需要保证pod使用的数据路径是不变的就可以了。
