### ISSUE TITLE
1.2.1 环境变量 NACOS_AUTH_ENABLE = false 不起作用？

### ISSUE THREAD

**Issue by baobeidaodao** [nacos-group/nacos-k8s#115]
使用 nacos-k8s 的 nfs 模式部署 nacos/nacos-server 中的 latest（ab9a49756f23）或者 1.2.1（139dc345eeaa），并且设置了环境变量 NACOS_AUTH_ENABLE = false ，之后访问管理平台，都需要登录。
是否有问题？

**Comment by paderlol** [comment]
这个开关不是控制管理平台是否登录，是用于客户端API调用是否需要鉴权，请去Nacos看下相关文档说明。

**Comment by baobeidaodao** [comment]
> 这个开关不是控制管理平台是否登录，是用于客户端API调用是否需要鉴权，请去Nacos看下相关文档说明。

@paderlol 明白了，感谢！！
