### ISSUE TITLE
使用cluster模式启动报找不到文件/home/nacos/conf/cluster.conf

### ISSUE THREAD

**Issue by sadiea** [nacos-group/nacos-k8s#116]
使用cluster模式启动报找不到文件/home/nacos/conf/cluster.conf

> 2020-04-21 18:12:36,954 ERROR read cluster conf fail
> 
> java.io.FileNotFoundException: /home/nacos/conf/cluster.conf (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at com.alibaba.nacos.core.utils.SystemUtils.readClusterConf(SystemUtils.java:124)
> 	at com.alibaba.nacos.core.listener.StartingSpringApplicationRunListener.logClusterConf(StartingSpringApplicationRunListener.java:142)
> 	at com.alibaba.nacos.core.listener.StartingSpringApplicationRunListener.contextPrepared(StartingSpringApplicationRunListener.java:92)
> 	at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:60)
> 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:374)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
> 	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
> 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
> 2020-04-21 18:12:37,958 INFO Nacos is starting...

**Comment by paderlol** [comment]
文件没写成功啊，你用的nfs的话就是nfs没有成功，或者你设置了clustertype，clustertype只能为none，可以看下已经close掉的issue里面有可能会找到你需要的

**Comment by sadiea** [comment]
我解决了，我改了nacos service里的headless的serviceName，statefulset里container环境变量SERVICE_NAME没改，所以可能访问不到headless服务导致cluster.conf写失败了
