### ISSUE TITLE
按照你们的文档进行k8s的编排部署后启动不起来host问题

### ISSUE THREAD

**Issue by chenxiangning** [nacos-group/nacos-k8s#117]
sh-4.2# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.244.3.37     nacos-0.nacos-headless.default.svc.cluster.local nacos-0

nacos-0.nacos-headless.default.svc.cluster.local 后面多了个空格外加nacos-0

######################################
节点报错
nacos is starting,you can check the /home/nacos/logs/start.out
2020/04/21 22:46:53 Have not found myself in list yet.
My Hostname: nacos-0.nacos-headless.default.svc.cluster.local
Hosts in list: nacos-headless.default.svc.cluster.local
2020/04/21 22:46:54 Have not found myself in list yet.
My Hostname: nacos-0.nacos-headless.default.svc.cluster.local
Hosts in list: nacos-headless.default.svc.cluster.local
2020/04/21 22:46:55 Have not found myself in list yet.

######## 我使用busybox起一个pod
/ # ping nacos-0.nacos-headless.default.svc.cluster.local
PING nacos-0.nacos-headless.default.svc.cluster.local (10.244.4.26): 56 data bytes
64 bytes from 10.244.4.26: seq=0 ttl=62 time=0.809 ms
64 bytes from 10.244.4.26: seq=1 ttl=62 time=0.508 ms
64 bytes from 10.244.4.26: seq=2 ttl=62 time=0.502 ms

都没问题,不知道怎么搞

**Comment by chenxiangning** [comment]
k8s集群版本 1.16

**Comment by chenxiangning** [comment]
nacos:latest

**Comment by chenxiangning** [comment]
[root@k8s-mm1 yaml]# kubectl exec -ti busybox -- nslookup nacos-0.nacos-headless.default.svc.cluster.local
Server:    10.0.0.2
Address 1: 10.0.0.2 kube-dns.kube-system.svc.cluster.local

Name:      nacos-0.nacos-headless.default.svc.cluster.local
Address 1: 10.244.0.12 nacos-0.nacos-headless.default.svc.cluster.local

**Comment by chenxiangning** [comment]
[root@k8s-mm2 nacos]# kubectl get pod
NAME                                      READY   STATUS             RESTARTS   AGE
busybox                                   1/1     Running            1          97m
mysql-master-nzscd                        1/1     Running            0          98m
mysql-slave-pwm2v                         1/1     Running            0          98m
nacos-0                                   1/1     Running            3          3m8s
nacos-1                                   0/1     CrashLoopBackOff   2          3m5s
nacos-2                                   0/1     CrashLoopBackOff   2          3m2s
nfs-client-provisioner-7d5dcb6557-5s4zr   1/1     Running            0          3m24s

**Comment by chenxiangning** [comment]
这三个节点之间就是内连上啊.怎么搞啊大佬

**Comment by chenxiangning** [comment]
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      protocol: TCP
      nodePort: 30848 
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.db.name: "nacos_devtest"
  mysql.port: "3306"
  mysql.user: "nacos"
  mysql.password: "nacos"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: nfs-client-provisioner
      initContainers:
        - name: peer-finder-plugin-install
          image: 192.168.238.211/cxn/nacos/nacos-peer-finder-plugin:1.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/home/nacos/plugins/peer-finder"
              name: plugindir
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: 192.168.238.211/cxn/nacos/nacos-server:1.14
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: SERVICE_NAME
              value: "nacos-headless"
            - name: DOMAIN_NAME
              value: "cluster.local"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848"
          volumeMounts:
            - name: plugindir
              mountPath: /home/nacos/plugins/peer-finder
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
  volumeClaimTemplates:
    - metadata:
        name: plugindir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: datadir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: logdir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
  selector:
    matchLabels:
      app: nacos

**Comment by paderlol** [comment]
不能用nodeport，只能设置为none，原因wiki里面有详细说明，如果非要用，请注释掉peer finder 插件

**Comment by yangmingqi218** [comment]
@paderlol 您好，请教一下，我使用none的方式，通过ingress暴露web服务，那集群外面的java项目怎么注册到集群内的nacos服务上呢

**Comment by paderlol** [comment]
注册ingress地址

**Comment by yangmingqi218** [comment]
@paderlol 您好   感谢您的回复    是不是需要传用户名密码？直接注册是失败的

**Comment by liangyuanpeng** [comment]
@yangmingqi218  我想用户密码是否需要传递是和你部署的环境有关，开启了认证自然是需要传递的。

**Comment by jackxiao007** [comment]
@chenxiangning chenxiangning 请问解决了吗？我也遇到同样的问题
