### ISSUE TITLE
k8s集群内搭建nacos，外部的java项目如何注册到集群内的nacos注册中心

### ISSUE THREAD

**Issue by yangmingqi218** [nacos-group/nacos-k8s#118]
您好，请教一下，我使用none的方式，通过ingress暴露web服务，那集群外面的java项目怎么注册到集群内的nacos服务上呢
通过ingress域名注册是失败的，是需要加用户名密码传参？

**Comment by paderlol** [comment]
你是说1.2.0开启auth吗？

**Comment by yangmingqi218** [comment]
不是这个意思，我是通过ingress暴露的nacos的web服务，现在浏览器可以访问nacos服务
但是外面的java项目通过ingress的地址注册不上nacos

**Comment by yangmingqi218** [comment]
正常来说是可以直接通过ingress地址注册的是么？

**Comment by paderlol** [comment]
你看下注册失败日志是什么，看看是不是nacos本身只能用域名加端口

**Comment by paderlol** [comment]
是啊

**Comment by yangmingqi218** [comment]
是开发反馈给我的，我只是想确定下是不是还有其他的端口提供注册，或者注册的时候会不会需要nacos的web登录使用的账号密码？

**Comment by paderlol** [comment]
不用，还有就是要确定你的集群成功了，集群成功要看下raft日志

**Comment by yangmingqi218** [comment]
好的，我确定下，raft日志是直接kubectl logs 能看见的么

**Comment by paderlol** [comment]
应该不行，只能exec 或者你挂卷了也可以看，控制台也可以看到，集群列表

**Comment by yangmingqi218** [comment]
![image](https://user-images.githubusercontent.com/38835550/80177247-b9f96100-862d-11ea-8a4e-a5bf4de27290.png)
您看些图片，这是不是失败了？

**Comment by yangmingqi218** [comment]
[root@nacos-0 logs]# tailf naming-raft.log
2020-04-24 13:14:30,001 WARN [IS LEADER] no leader is available now!

2020-04-24 13:14:45,000 WARN [IS LEADER] no leader is available now!

2020-04-24 13:15:00,000 WARN [IS LEADER] no leader is available now!

2020-04-24 13:15:15,000 WARN [IS LEADER] no leader is available now!

2020-04-24 13:15:30,000 WARN [IS LEADER] no leader is available now!

2020-04-24 13:15:45,000 WARN [IS LEADER] no leader is available now!

2020-04-24 13:16:00,000 WARN [IS LEADER] no leader is available now!

2020-04-24 13:16:15,000 WARN [IS LEADER] no leader is available now!

2020-04-24 13:16:30,000 WARN [IS LEADER] no leader is available now!

**Comment by paderlol** [comment]
选主没成功，所以nacos集群没启动成功，这个问题，你先看下关闭issue的处理吧，可能会找到你需要的

**Comment by yangmingqi218** [comment]
好的  谢谢

**Comment by paderlol** [comment]
不客气，先看下close的issue里面，不行再留言给我

**Comment by yangmingqi218** [comment]
您好，我是使用的nacos-quick-start.yaml起的服务，mysql自己挂载的云盘，这个yaml里面没有找到健康检查的配置参数

**Comment by yangmingqi218** [comment]
![image](https://user-images.githubusercontent.com/38835550/80178513-fc706d00-8630-11ea-8693-3e978d2d0c2e.png)
这是nacos.log的内容

**Comment by yangmingqi218** [comment]
![image](https://user-images.githubusercontent.com/38835550/80178603-33468300-8631-11ea-84d2-9b2017cd9aa1.png)
![image](https://user-images.githubusercontent.com/38835550/80178611-38a3cd80-8631-11ea-9c94-5d38a5f1b1b4.png)
都是通的，也有监听

**Comment by yangmingqi218** [comment]
![image](https://user-images.githubusercontent.com/38835550/80178673-625cf480-8631-11ea-9cd8-2912d27e9071.png)
这是config-server.log的内容，应该是与健康检查有关系，但是这个quikstart的yaml里面没有健康检查的配置选项

**Comment by paderlol** [comment]
你日志里面都告诉你了啊，你集群配置错了，你把命名空间都改了，你集群里面配置得nacos节点也要改啊

**Comment by yangmingqi218** [comment]
可以了，谢谢您

**Comment by paderlol** [comment]
不客气




| |
浮夸
|
|
邮箱：huangmnlove@163.com
|

签名由 网易邮箱大师 定制

在2020年04月24日 14:01，yangmingqi218 写道：

可以了，谢谢您

**Comment by yangmingqi218** [comment]
![image](https://user-images.githubusercontent.com/38835550/80180852-3c861e80-8636-11ea-836a-ddd9c536bf84.png)
您好，请问这是正常么

**Comment by yangmingqi218** [comment]
![image](https://user-images.githubusercontent.com/38835550/80181372-5116e680-8637-11ea-8460-d89df86b310e.png)
注册  发布和获取都没问题，之后服务发现报501，请问这是正常的么

**Comment by paderlol** [comment]
这需要你自己看日志分析下

**Comment by yangmingqi218** [comment]
您好，我使用curl注册显示是ok，研发第一次本地注册没问题，但是第二次使用本地注册nacos，代码里面定义的是url，但是run的时候显示的是http://url:8848
![image](https://user-images.githubusercontent.com/38835550/80190340-b9b98f80-8646-11ea-9383-8eafd164c5ae.png)

**Comment by yangmingqi218** [comment]
这种情况您遇到过么，是nacos配置有问题么

**Comment by paderlol** [comment]
没遇到过，既然本地第一次能成功，那应该证明没有问题，不知道第二次是否做了什么改动，或者是client里面默认已经带了端口

**Comment by yangmingqi218** [comment]
我把url后面加上:80就好了，不然会自动转8848这个端口，这是不是nacos的bug😂

**Comment by paderlol** [comment]
你是不是写域名的时候，没有填http头？

**Comment by paderlol** [comment]
你得配置http://url这样才行，不然会认为你是一个ip

**Comment by yangmingqi218** [comment]
哦哦   明白了   谢谢您，我关闭case了，谢谢您

**Comment by yangmingqi218** [comment]
不对，前面如果加http的话，run的时候会http://http://url

**Comment by paderlol** [comment]
我知道了，这个好像只有阿里云上才有这个功能

**Comment by paderlol** [comment]
但是我很好奇，你第一次为什么成功了

**Comment by yangmingqi218** [comment]
第一次用的就是:80的方式，后来以为不用就删了，就绕进去了

**Comment by paderlol** [comment]
嗯，好的

**Comment by yangmingqi218** [comment]
closed
