### ISSUE TITLE
为什么节点一直注册不上去？

### ISSUE THREAD

**Issue by apicescn** [nacos-group/nacos-k8s#121]
如下图，为什么一切都正常，并可以访问，但这个节点列表一直为空，这样的话，服务就无法注册上去，请问如何解决，查看了各个日志，发现一切都正常，部署也是参加官方进行的！求救~
![image](https://user-images.githubusercontent.com/28082126/80484865-feb52d00-898a-11ea-9850-a79df073ac96.png)

**Comment by paderlol** [comment]
集群没启动成功

**Comment by koy1619** [comment]
`java.lang.IllegalStateException: unable to find local peer: nacos-1.nacos-headless.default.svc.cluster.local.:8848, all peers: [nacos-0.nacos-headless.default.svc.cluster.local:8848, nacos-1.nacos-headless.default.svc.cluster.local:8848, nacos-2.nacos-headless.default.svc.cluster.local:8848]`


这个是什么原因？ 

pod之间域名相互能ping通

**Comment by paderlol** [comment]
你的dns带点，需要自己去移除，或者设置kubectl的dns的domain

**Comment by koy1619** [comment]
@paderlol  正解！ 灰常感谢！多了个.   😂

kubelet.config

clusterDomain: cluster.local.

**Comment by paderlol** [comment]
已解决
