### ISSUE TITLE
 ClusterIP   None 那么pod里面运行的微服务怎么连nacos？

### ISSUE THREAD

**Issue by yorkexing** [nacos-group/nacos-k8s#123]
nacos-headless   ClusterIP   None 后
外部通过ingress访问
内部通过什么访问呀？

**Comment by paderlol** [comment]
内部？同一个namespace？那就通过内部域名来访问

**Comment by yorkexing** [comment]
nacos集群部署好之后
1. 访问nacos控制台，是通过ingress配置的域名，域名我们做了办公网络DNS解析
2. 如果是本地开发idea启动，直接是配置的这个域名
3. 部署在K8S里面的微服务连接nacos集群，通过这个域名是解析不到的，但是也是应该通过 nacos-headless这个svc连接到nacos集群，那么是通过什么方式呢？现在ClusterIP None也没有IP的嘛？
     内部域名是什么？是自动生成的嘛？

**Comment by paderlol** [comment]
嗯，跟docker内部访问方式差不多

**Comment by yorkexing** [comment]
学习了下coreDns，搞定了，感谢！

**Comment by siaron** [comment]
> 学习了下coreDns，搞定了，感谢！

coreDns 怎么搞定的. 能分享下不?
