### ISSUE TITLE
已有自建数据库的情况下；K8S如何只部署nacos集群，不部署数据库？

### ISSUE THREAD

**Issue by koy1619** [nacos-group/nacos-k8s#124]
比如增加一个 `mysql.db.host` 参数？

**Comment by paderlol** [comment]
参照nacos docker的readme，里面有文档

**Comment by koy1619** [comment]
测试已经通过，提了PR

https://github.com/nacos-group/nacos-k8s/pull/125

**Comment by kpioneer123** [comment]
自建数据库 nacos-mysql.sql 是手动创建 还是代码自动生成 ，如果手动创建 nacos-mysql.sql 文件可以发一份么。

**Comment by zerols** [comment]
启用数据库 默认的就一个pod 是否有类似mysql主从的配置项
