### ISSUE TITLE
采用k8s方式部署nacos，启动之后发现端口未监听，查看日志提示数据库连接不上，但是检查账号，密码都是通的，端口也是通的，但是我采用的是外部mysql8.0，是因为这个原因嘛？

### ISSUE THREAD

**Issue by bryant-rh** [nacos-group/nacos-k8s#132]
![image](https://user-images.githubusercontent.com/43403977/84137644-8c526500-aa7f-11ea-92eb-3715b7ca5fb2.png)

**Comment by paderlol** [comment]
是的，nacos在k8s上目前无法支持mysql8

**Comment by bryant-rh** [comment]
> 是的，nacos在k8s上目前无法支持mysql8

好的，谢谢

**Comment by bryant-rh** [comment]
nacos在k8s上目前无法支持mysql8
