### ISSUE TITLE
Unable to update configuration when pod run as non-root

### ISSUE THREAD

**Issue by wwyhy** [nacos-group/nacos-k8s#133]
Hi,

I deployed nacos cluster by helm chart(using storageclass by azure cloud), I can create a new configration from UI. 

![image](https://user-images.githubusercontent.com/83105/85118241-aa278300-b252-11ea-9029-b04eab963e0e.png)

But I got a error when update a configuration, we are run the pod with non-root account. Is it possible to update the docker to fix this? here is the error log:

![image](https://user-images.githubusercontent.com/83105/85117916-2cfc0e00-b252-11ea-86ad-099190e52aad.png)

Thanks!
Br, wwyhy

**Comment by paderlol** [comment]
这个看着跟docker没什么关系，这似乎是因为这个目录并没有挂卷吧

**Comment by wwyhy** [comment]
从chart里看， 没有要求挂载这个卷.
我猜是因为： 如果用容器以root启动，他会自动创建这个临时目录.
                        但我们是以非root启动的， 所以没有权限去创建这个临时目录，就导致报错。

**Comment by paderlol** [comment]
我这个是例子啊，你们需要自己去根据自己的需求扩展下的

**Comment by paderlol** [comment]
这种目录一般都需要整体挂下卷吧，我演示的时候没有挂那么粗粒度

**Comment by wwyhy** [comment]
我验证了下， 确实是这个问题， 用root启动， 就没有问题。

**Comment by paderlol** [comment]
Root启动 k8s的pod？

**Comment by paderlol** [comment]
你做的更新配置操作吗？我刚刚用其他卷试了下没有这个问题

**Comment by wwyhy** [comment]
是的， root启动nacos pod 就没有问题。 
用非root启动就有问题

**Comment by paderlol** [comment]
我用的AWS EKS实验 还有 kube都没有这个问题

**Comment by paderlol** [comment]
你是想docker 设置privileged？

**Comment by wwyhy** [comment]
不是哈， 我们这边策略是pod里不允许以root允许。

我都没有挂这个目录（root/non-root启动pod）， 

这个临时目录应该是pod运行后由某个操作触发创建的，如：更新配置。
如果用root启动的pod。 有权限创建这个目录。
如果用非root启动pod，  没有权限在/home/nacos目录下创建这个目录导致的。

所以这个问题在以非root启动pod的时候要提前处理： 
比如: 1) 再挂载一个目录， 作为/home/nacos/work
2) 把3个挂载点换成一个/home/nacos
3) 改配置让这个目录指向某个挂载点下的目录,data, logs
等等方案。

**Comment by paderlol** [comment]
可以使用第二个方案，不过如果你用了peerfinder就只能第一个方案了

**Comment by paderlol** [comment]
第三个方案可以在conf目录中挂一个配置文件custom.properties来配置server.tomcat.basedir

**Comment by paderlol** [comment]
第三个方案可以在conf目录中挂一个配置文件custom.properties来配置server.tomcat.basedir
