### ISSUE TITLE
在k8s部署nacos，报server is STARTING now, please try again later

### ISSUE THREAD

**Issue by warlockhades** [nacos-group/nacos-k8s#134]
在pod中执行命令curl -X GET "http://localhost:8848/nacos/v1/ns/raft/state"
回显server is STARTING now, please try again later!
查看naming-raft.log
报no leader is available now!

查看了kubelet参数 clusterDomain值是“cluster.local”

os.name: EulerOS_2.0_SP5
os.version: 3.10.0-862.14.1.2.h249.eulerosv2r7.x86_64
kubeletVersion: v1.13.10-r1-CCE2.0.28.B001
containerRuntimeVersion: docker://18.9.0
镜像中的nacos版本: 1.0.0

**Comment by paderlol** [comment]
你用的是哪个文件启动的？

**Comment by warlockhades** [comment]
> 你用的是哪个文件启动的？

https://github.com/nacos-group/nacos-k8s/blob/9bc5eb1de0d88f7f58ee266ec4b97a2d0dc4ffcc/deploy/nacos/nacos-pvc-nfs.yaml
修改了spec.ports.port
修改了spec.replicas
修改了镜像相关配置

**Comment by paderlol** [comment]
你修改了端口？

**Comment by warlockhades** [comment]
> 你修改了端口？

spec:
  ports:
    - port: 38848
      name: server
      targetPort: 8848

**Comment by paderlol** [comment]
端口不能更改 因为用了plugin插件 只能和nacos应用保持一致,因为里面获取变量是根据NACOS_SERVER_PORT

**Comment by warlockhades** [comment]
> 端口不能更改 因为用了plugin插件 只能和nacos应用保持一致,因为里面获取变量是根据NACOS_SERVER_PORT

把端口改回去了 仍然报一样的错
spec:
ports:
- port: 8848
name: server
targetPort: 8848

deploy/nfs/deployment.yaml
deploy/mysql/mysql-master-nfs.yaml
deploy/mysql/mysql-slave-nfs.yaml
上述文件中配置的nfs路径中生成了文件 能否认为nfs路径配置没有问题

**Comment by paderlol** [comment]
还有不要增加clustertype

**Comment by paderlol** [comment]
最好把日志里面错误详细信息贴出来

**Comment by paderlol** [comment]
还有把readiness 和liveness去掉，这个api有问题的

**Comment by warlockhades** [comment]
> 还有把readiness 和liveness去掉，这个api有问题的

去掉这两个探针问题解决，多谢
