### ISSUE TITLE
quick-startup.sh MYSQL_SERVICE_HOST 不存在导致服务启动失败

### ISSUE THREAD

**Issue by jsjxhj** [nacos-group/nacos-k8s#136]
./quick-startup.sh 脚本启动本地mysql和nacos集群，启动失败
原因：nacos-quick-start.yaml缺失MYSQL_SERVICE_HOST 环境变量的配置
解决方案：
      ConfigMap 里面加上 mysql.db.hostname: "mysql"
      StatefulSet.spec.containers.env 加上
          `- name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.hostname`

**Comment by paderlol** [comment]
你是用的你自己本地的数据库？如果是自己自定义的数据库就是这样的，就需要你上面的这些操作，如果是直接用的quickstart.sh启动就会用例子数据库
