### ISSUE TITLE
挂载目录data的用处

### ISSUE THREAD

**Issue by EverCurse** [nacos-group/nacos-k8s#137]
既然数据都持久化到数据库了 那么这个目录 /home/nacos/data 挂载出来有什么意义呢？ 如果不挂载 会有什么影响？ 谢谢

**Comment by paderlol** [comment]
注册中心的选举数据

**Comment by EverCurse** [comment]
@paderlol 我只需要用到配置管理 是不是这个目录就不用挂载了 丢了也不影响我配置管理的使用？

**Comment by paderlol** [comment]
不影响
