### ISSUE TITLE
创建 ServiceAccount 和部署 NFS-Client Provisioner 错误！

### ISSUE THREAD

**Issue by ppqbin** [nacos-group/nacos-k8s#141]
我的版本：Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

# 创建 ServiceAccount 和部署 NFS-Client Provisioner
kubectl create -f deploy/nfs/deployment.yaml

#提示错误：
error validating "deploy/nfs/deployment.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by paderlol** [comment]
请重新更新下pull一下工程 这个是Kubernetes 1.16升级后强制需要spec填写selector属性,已经有社区的小伙伴兼容了 #77
