### ISSUE TITLE
MySQL数据库容器表结构获取

### ISSUE THREAD

**Issue by zjcnew** [nacos-group/nacos-k8s#143]
我想使用外部的MySQL数据库，哪里可以获取到nacos数据库的表结构sql文件

**Comment by paderlol** [comment]
Nacos github 里面有的

**Comment by paderlol** [comment]
或者自己下一个Nacos的release包，里面也是有的

**Comment by zjcnew** [comment]
为什么Data ID这里模糊搜索搜不到任何内容

![企业微信截图_20200806180303](https://user-images.githubusercontent.com/22335594/89519541-1c5a2400-d80f-11ea-80ed-1edaa7b95db2.png)

**Comment by paderlol** [comment]
这个可能搜索用的准确查询，麻烦把这个issue，提到官方
