### ISSUE TITLE
nacos集群leader选举失败

### ISSUE THREAD

**Issue by DanceKiddle** [nacos-group/nacos-k8s#145]
环境：
nacos镜像：nacos/nacos-server:1.3.1
k8s集群：1.16
nacos部署方式：  kubectl apply -f nacos-no-pvc.yaml

问题：
发现nacos控制台登录缓慢，并且服务有时注册不进去。
注册不进去的服务后台日志报错：
`Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([nacos-headless.default.svc:8848]) tried: java.net.SocketTimeoutException: Read timed out
`
nacos控制台中查看  集群管理->节点列表 如下：

nacos-0.nacos-headless.default.svc.cluster.local.:8848 | UP | 节点元数据
nacos-0.nacos-headless.default.svc.cluster.local:8848 | UP | 节点元数据
nacos-1.nacos-headless.default.svc.cluster.local:8848 | UP | 节点元数据
nacos-2.nacos-headless.default.svc.cluster.local:8848 | UP | 节点元数据

进入nacos-0容器中cat naming-raft.log显示错误：
`2020-08-13 18:19:00,001 WARN [IS LEADER] no leader is available now!

2020-08-13 18:19:04,710 INFO leader timeout, start voting,leader: null, term: 269

2020-08-13 18:19:04,714 ERROR NACOS-RAFT vote failed: caused: can not find peer: nacos-0.nacos-headless.default.svc.cluster.local.:8848;, url: http://nacos-1.nacos-headless.default.svc.cluster.local:8848/nacos/v1/ns/raft/vote

2020-08-13 18:19:05,897 INFO received illegitimate vote, voter-term:270, votee-term:270

2020-08-13 18:19:05,898 INFO received approve from peer: {"ip":"nacos-0.nacos-headless.default.svc.cluster.local.:8848","voteFor":"nacos-0.nacos-headless.default.svc.cluster.local.:8848","term":270,"leaderDueMs":15157,"heartbeatDueMs":4000,"state":"CANDIDATE"}

`

请教下这种多了个加.的节点是否正常，并且该错误怎么解决？

**Comment by paderlol** [comment]
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点

**Comment by paderlol** [comment]
这个是你kubernetes根域名导致的
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by paderlol** [comment]
这个是你kubernetes根域名导致的
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by paderlol** [comment]
这个是你kubernetes根域名导致的
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by paderlol** [comment]
这个是你kubernetes根域名导致的
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by paderlol** [comment]
这个是你kubernetes根域名导致的
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by paderlol** [comment]
这个是你kubernetes根域名导致的
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by paderlol** [comment]
这个是你kubernetes根域名导致的
两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by DanceKiddle** [comment]
> 这个是你kubernetes根域名导致的
> 两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
> 第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

可以了，建议写在yaml注释里

> 这个是你kubernetes根域名导致的
> 两个方案，第一，kubernetes的 dns cluster.domain属性，可自行百度，有这个方案。
> 第二 修改部署Yaml里面NACOS_SERVERS环境变量，给配置的每个节点local后面加个点，像这样nacos-0.nacos-headless.default.svc.cluster.local.:8848

可以了，看到不带.的三个节点都是up状态，并且部分服务可以注册，所以没想到是这个问题，感谢。
