### ISSUE TITLE
请问/home/nacos/data 目录的持久化一定要ReadWriteMany 嘛？

### ISSUE THREAD

**Issue by windghoul** [nacos-group/nacos-k8s#148]
nacos 的这个目录作用是什么呢？需要三个副本共享这个路径嘛？

**Comment by paderlol** [comment]
不行的，建议使用Statefulset部署，因为data里面存放的raft日志数据，以及配置

**Comment by windghoul** [comment]
需要使用ReadWriteMany，我是用ReadWriteOnce ，这样可以嘛
