### ISSUE TITLE
修复deploy/quick-start.yaml 中pod反亲和性编写错误

### ISSUE THREAD

**Issue by windghoul** [nacos-group/nacos-k8s#150]
![image](https://user-images.githubusercontent.com/16053291/91381057-04e3e900-e859-11ea-965d-a829d96b2c83.png)
修复deploy/quick-start.yaml 、no-pvc.yaml中pod反亲和性编写错误
修复 deploy/quick-start.yaml、no-pvc.yaml  service 的headless svc 写法
优化了ingress 的写法，不需要部署两个svc 进行ingress 暴露
pr 已交  #149

**Comment by paderlol** [comment]
已合并,感谢PR
