### ISSUE TITLE
升级到1.3.2版本后报错

### ISSUE THREAD

**Issue by kengan** [nacos-group/nacos-k8s#155]
原有已经在k8s集群部署了1.2.1版本的nacos，具体yaml如下：

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: jts-nacos
spec:
  serviceName: nacos
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8snacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server:1.3.2
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: server
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name:  MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                  configMapKeyRef:
                    name: nacos-cm
                    key:  mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                    configMapKeyRef:
                      name: nacos-cm
                      key: mysql.password
            - name:  MYSQL_SERVICE_HOST
              valueFrom:
                    configMapKeyRef:
                      name: nacos-cm
                      key:  mysql.host
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos.jts-nacos.svc.cluster.local.:8848 nacos-1.nacos.jts-nacos.svc.cluster.local.:8848 nacos-2.nacos.jts-nacos.svc.cluster.local.:8848"
  selector:
    matchLabels:
      app: nacos

一切正常运行，
今天把镜像升级到1.3.2，能部署成功，没有任何异常，但进入管理后台，点击集群节点时弹出错误：
no such api:GET:/nacos/v1/ns/operator/cluster/states
请问如何解决

**Comment by paderlol** [comment]
首先尝试下清除浏览器缓存，大概率是页面还使用的缓存的js调用接口
