### ISSUE TITLE
readiness配置

### ISSUE THREAD

**Issue by HiroC222** [nacos-group/nacos-k8s#158]
现在还有什么机制做服务探活吗，如果不配置readinessProbe，当有nacos节点挂掉，集群内通过svc名字连接nacos的就会异常吧。

**Comment by HiroC222** [comment]
![QQ录屏20200928132152 mp4_20200928_133222](https://user-images.githubusercontent.com/4082983/94394116-1dfcf400-018f-11eb-8101-30a31ec2c223.gif)

一共三个节点，每次刷新返回结果都不同，第二次刷新时，访问日志返回503，该异常节点依然能被请求到

**Comment by paderlol** [comment]
可以通过spring boot自己的应用探活来做

**Comment by HiroC222** [comment]
比如我截图里的报错， 三个nacos节点都是活得，但是从nginx访问日志来看，其中有一个节点返回503了。  从spring boot 的 health里能探测出来么。。

**Comment by paderlol** [comment]
应该是可以的，毕竟只是单纯的探测应用是否up起来了

**Comment by HiroC222** [comment]
现在我遇到的问题是，服务起来了，但是调用里面接口不正常，单纯探测up还不能满足。。
比如这个接口：/nacos/v1/ns/catalog/services?withInstances=false&pageNo=1&pageSize=10

**Comment by paderlol** [comment]
那估计没法满足，我建议你可以把你的需求提到Nacos那，仔细描述下你的需求。

**Comment by HiroC222** [comment]
嗯嗯 非常感谢大佬解答，我close了
