### ISSUE TITLE
quick-startup.sh have some bug

### ISSUE THREAD

**Issue by wshzp12345** [nacos-group/nacos-k8s#16]
can't use quick-startup.sh to run nacos cluster, because in that code 
`
echo "nacos quick startup"
kubectl create -f ./deploy/nacos/nacos-quick-start.yamlemptyDirs will possibly result in a loss of data`

suppose to be
`
echo "nacos quick startup"
kubectl create -f ./deploy/nacos/nacos-quick-start.yaml`

**Comment by JoeToffler** [comment]
Yes,that's true
