### ISSUE TITLE
在nacos的StatefulSet模板里面，没有暴露7848端口，导致集群无法通讯进行选举，集群模式不可用。

### ISSUE THREAD

**Issue by bigbang20061** [nacos-group/nacos-k8s#161]
在nacos的StatefulSet模板里面，没有暴露7848端口，导致集群无法通讯进行选举，集群模式不可用。
希望在里面加上这个7848端口。

**Comment by paderlol** [comment]
好的

**Comment by paderlol** [comment]
我看了下暂时集群选举是没有跟这个rpc有关系的，这个应该是在配置中心使用嵌入式存储的时候需要的jraft的端口

**Comment by bigbang20061** [comment]
> 我看了下暂时集群选举是没有跟这个rpc有关系的，这个应该是在配置中心使用嵌入式存储的时候需要的jraft的端口

但是不添加这个端口的话，会提示：
INFO leader timeout, start voting,leader: null, term: 1
WARN [IS LEADER] no leader is available now!

添加了这个7848端口之后整个nacos集群就正常了。

**Comment by paderlol** [comment]
1.3.2吗？我已经修复了，不过按理是不会的，因为除非你用了embedded的模式

**Comment by bigbang20061** [comment]
使用的是nacos/nacos-server:latest版本，记录显示是 9/25/2020 at 11:12 am发布的
