### ISSUE TITLE
集群节点状态异常，导致配置数据在集群间同步异常

### ISSUE THREAD

**Issue by wanghuigithub** [nacos-group/nacos-k8s#165]
通过观察com.alibaba.nacos.core.cluster.ServerMemberManager的allMembers方法，发现。
在某个节点上，只有本节点的状态是UP。其他节点状态都是DOWN。
例如：A、B、C三个节点
A节点结果：A(UP)   B(DOWN)  C(DOWN)
B节点结果：A(DOWN)   B(UP)  C(DOWN)
C节点结果：A(DOWN)   B(DOWN)  C(UP)

并且部署出的集群的cluster.conf文件中内容和文档中不一样，多出了一条boss记录。
nacos-0.nacos-headless.default.svc.boss.twl:8848
nacos-0.nacos-headless.default.svc.cluster.local:8848
nacos-1.nacos-headless.default.svc.cluster.local:8848
nacos-2.nacos-headless.default.svc.cluster.local:8848

**Comment by paderlol** [comment]
是因为你们的集群的后缀就是boss.twl

**Comment by wanghuigithub** [comment]
> 是因为你们的集群的后缀就是boss.twl

官网文档中部署完成后，cluster.conf文件只有三条记录。
我的部署完后，有四条。
这个原因是什么

**Comment by paderlol** [comment]
因为nacos本身会去匹配你们本地的host，如果不一样就会新增进去

**Comment by paderlol** [comment]
暂时没有回复,无法得知是否已经正常,暂时关闭issue

**Comment by xlzlyyy** [comment]
碰到同样的问题，部署方式是用docker，开始用的桥接模式，用ip注册，会有四条记录。
然后改成来net=host,就变成3条来。
单是一直还是有状态变化问题：
在某个节点上，只有本节点的状态是UP。其他节点状态都是DOWN。
例如：A、B、C三个节点
A节点结果：A(UP) B(DOWN) C(DOWN)
B节点结果：A(DOWN) B(UP) C(DOWN)
C节点结果：A(DOWN) B(DOWN) C(UP)

**Comment by xlzlyyy** [comment]
> 通过观察com.alibaba.nacos.core.cluster.ServerMemberManager的allMembers方法，发现。 在某个节点上，只有本节点的状态是UP。其他节点状态都是DOWN。 例如：A、B、C三个节点 A节点结果：A(UP) B(DOWN) C(DOWN) B节点结果：A(DOWN) B(UP) C(DOWN) C节点结果：A(DOWN) B(DOWN) C(UP)
> 
> 并且部署出的集群的cluster.conf文件中内容和文档中不一样，多出了一条boss记录。 nacos-0.nacos-headless.default.svc.boss.twl:8848 nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848

你好，你这个问题处理好了吗，是怎么处理的。
