### ISSUE TITLE
部署多个节点时，如何做到节点IP变化对使用方无感知

### ISSUE THREAD

**Issue by wanghuigithub** [nacos-group/nacos-k8s#167]

**Comment by paderlol** [comment]
可以使用nacos address功能，具体可以去官网看下或者

**Comment by wanghuigithub** [comment]
> 可以使用nacos address功能，具体可以去官网看下或者

server节点IP发生变化时，会自动更新给server address么

**Comment by paderlol** [comment]
客户端会定时轮询获取

**Comment by wanghuigithub** [comment]
> 客户端会定时轮询获取

没太明白，能帮贴下文档地址么，在官网没有找到server address相关的介绍。
server ip节点发生变化了，客户端为什么还可以建立连接呢

**Comment by paderlol** [comment]
是通过一个服务接口获取的

**Comment by paderlol** [comment]
具体你可以在nacos提一个issue问下

**Comment by paderlol** [comment]
已转移至Nacos Issue
