### ISSUE TITLE
after setup a the nacos cluster in the K8S， how could application register in nacos

### ISSUE THREAD

**Issue by wshzp12345** [nacos-group/nacos-k8s#17]
TWO point, 
first, definitely ,we can use the DNS, for example: 
nacos-0.nacos-headless.default.svc.cluster.local

BUT  this is a cluster and the auto-scale is enable under  nacos-pvs-nfs deployment.

SO , How could we use the Nacos cluster, please give a example.

**Comment by paderlol** [comment]
Pardon？I don't quite understand what you mean by an example

**Comment by wshzp12345** [comment]
I mean how to set a VIP which can loadbalance the nacos correctly under auto-scale situation

**Comment by paderlol** [comment]
you can see the other branch which name is [feature_ingress](https://github.com/nacos-group/nacos-k8s/tree/feature_ingress)

**Comment by wshzp12345** [comment]
thanks , pls check this issue:
[https://github.com/nacos-group/nacos-k8s/issues/15](url)
