### ISSUE TITLE
未同步更新的helm README

### ISSUE THREAD

**Issue by yl-yue** [nacos-group/nacos-k8s#172]
https://github.com/nacos-group/nacos-k8s/blob/master/helm/README.md

**启动错误：**
`Failed to install app nacos. Error: Service "nacos-cs" is invalid: spec.ports[1].nodePort: Invalid value: 7848: provided port is not in the valid range. The range of valid ports is 30000-32767`

在README.md文件与values.yaml文件描述中并未找到相关端口说明，是否需要NodePort端口还是仅用作集群内部通信。

**Comment by paderlol** [comment]
启动错误？是指？

**Comment by yl-yue** [comment]
抱歉刚才点快了，错误信息没写完

**Comment by yl-yue** [comment]
使用helm v3启动，应答如下：

|key											|value		|
|--												|--			|
|global.mode									|standalone	|
|image.tag										|1.3.2		|
|mysql.persistence.claim.spec.storageClassName	|longhorn	|
|mysql.persistence.enabled						|true		|
|persistence.data.storageClassName				|longhorn	|
|persistence.enabled							|true		|
|persistence.storageClassName					|longhorn	|

**Comment by paderlol** [comment]
你上面这个nodeport是你设置7848这个端口做nodeport吗？

**Comment by yl-yue** [comment]
```yml
service:
  #type: ClusterIP
  type: NodePort
  port: 8848
  nodePort: 30000
  rpcPort: 7848
```

我看values.yaml文件中默认值是这样的，我没有填写应答应该会用默认值

**Comment by yl-yue** [comment]
之前是用的 https://apphub.aliyuncs.com 这个仓库里面的nacos模板部署的，但由于未更新不能部署1.3.2版本的nacos

**Comment by paderlol** [comment]
好的，我知道了，这里有点问题，我修改下。

**Comment by yl-yue** [comment]
好的，我也研究下这方面的知识，希望能帮助到你定位错误或修改。

可以考虑为仓库添加helm模板版本概念，保障仓库的高可用性，像这样：
![image](https://user-images.githubusercontent.com/39790401/98319763-7049f400-201c-11eb-9d5f-f90c4c93dbca.png)

**Comment by paderlol** [comment]
好的
