### ISSUE TITLE
怎么配置自己部署的MySQL的地址

### ISSUE THREAD

**Issue by wanghuigithub** [nacos-group/nacos-k8s#173]
怎么配置自己部署的MySQL的地址

**Comment by paderlol** [comment]
参考docker的readme

**Comment by duhongx** [comment]
建议是部署好的nacos-0里位于/home/nacos/conf/application.properties文件拷贝出来修改成需要的配置，然后基于这个文件创建configmap，再修改nacos的statefulset把configmap挂载到pod里，最后把nacos-cm相关的配置干掉就行了。
![Uploading image.png…]()
