### ISSUE TITLE
环境变量MYSQL_MASTER_SERVICE_HOST读取失败

### ISSUE THREAD

**Issue by wanghuigithub** [nacos-group/nacos-k8s#174]
配置了MYSQL_MASTER_SERVICE_HOST环境变量的值。但是没有被读取。如图：
![image](https://user-images.githubusercontent.com/11936135/98370030-db271980-2074-11eb-8b4d-da0773244c77.png)

![image](https://user-images.githubusercontent.com/11936135/98370068-f134da00-2074-11eb-91ed-618a7df3cc87.png)

但是从日志中看，配置的值并没有被获取到，如图
![image](https://user-images.githubusercontent.com/11936135/98370130-0b6eb800-2075-11eb-88bf-e1b71f4216e5.png)

图zh中IP是我pod的IP。不是MYSQL_MASTER_SERVICE_HOST配置的值

**Comment by paderlol** [comment]
这个属性已经被废弃了，麻烦看下docker的readme

**Comment by wanghuigithub** [comment]
> 这个属性已经被废弃了，麻烦看下docker的readme

nacos-docker的readme中没有对MYSQL_MASTER_SERVICE_HOST的说明
nacos-docker readme地址：
https://github.com/nacos-group/nacos-k8s/blob/master/README-CN.md

**Comment by wanghuigithub** [comment]
已经配置了MYSQL_SERVICE_HOST，日志中的报错为什么是访问本地被拒绝呢

**Comment by wanghuigithub** [comment]
使用nacos-k8s部署

**Comment by paderlol** [comment]
你这个上面看不到完整的配置信息，而且你在k8s里面怎么访问的是局域网的地址？然后数据库脚本有没有自己加载，请按照现在k8s的例子部署，你那个里面写的太乱了

**Comment by paderlol** [comment]
参考工程下面这个例子deploy/nacos/nacos-no-pvc.yaml

**Comment by wanghuigithub** [comment]
我们的k8s集群内外的ip是打通的

**Comment by wanghuigithub** [comment]
没有加载自己的数据库脚本

**Comment by wanghuigithub** [comment]
我现在的现象就是，配置的MYSQL_SERVICE_HOST变量。但是报错日志里面打印的确实pod的IP。而不是MYSQL_SERVICE_HOST配置的值。这个很奇怪

**Comment by paderlol** [comment]
要自己初始化数据库脚本，自定义数据库Nacos不会初始化数据库脚本，至于你想确定数据库地址，你可以进入容器输出一下MYSQL_SERVIVE_HOST，并且可以看看conf/application里面数据库的变量是不是引用的你配置的这些

**Comment by wanghuigithub** [comment]
好的，主要是容器现在起不来，😹

**Comment by paderlol** [comment]
额，然后你们用的镜像是最新的吗？

**Comment by wanghuigithub** [comment]
1.4.0

**Comment by paderlol** [comment]
账号密码正确以及数据库实例名还有自己要把表建好，基本上就没问题了

**Comment by wanghuigithub** [comment]
![image](https://user-images.githubusercontent.com/11936135/98436285-19741580-2115-11eb-8f77-e6d2566f8860.png)
主要这个IP不是我配置的环境变量的值。比较懵

**Comment by wanghuigithub** [comment]
没有访问到正确的MySQL的地址

**Comment by paderlol** [comment]
这个地方是显示你自己客户端的IP的，他是说你客户端这个用户通过这个IP连接数据库被拒绝，并不是指连数据库的地址，所以你现在需要自己排查是密码不对还是数据库权限没设置好。

**Comment by paderlol** [comment]
Access denied for user 'nerko'@'发出连接的客户端IP'

**Comment by wanghuigithub** [comment]
哦，醍醐灌顶。我check下，谢谢

**Comment by paderlol** [comment]
已解决

**Comment by yusiwen** [comment]
@paderlol 您好！我看代码仓库master分支的`deployt/nacos/nacos-pvc-nfs.yaml`文件里并没有设置mysql数据库Host的地方？这样statefulsets启动后nacos是如何连到mysql服务的？搞不明白？
