### ISSUE TITLE
k8s nacos ingress 502

### ISSUE THREAD

**Issue by cheungjingyu** [nacos-group/nacos-k8s#177]
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nacos-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: www.warp.nacos
      http:
        paths:
          - path: /nacos
            backend:
              serviceName: nacos-headless
              servicePort: 8848
====
http://www.warp.nacos:31597/nacos/index.html
===
result
502 Bad Gateway

**Comment by cheungjingyu** [comment]
Is this what is the reason

**Comment by fsjwin** [comment]
are you resolved it , i see this queue yet!!????

**Comment by fsjwin** [comment]
below is the log :
2020/11/24 12:49:30 [error] 9574#9574: *8502838 connect() failed (111: Connection refused) while connecting to upstream, client: 10.244.1.0, server: www.nacos.com, request: "GET /nacos HTTP/1.1", upstream: "http://10.244.5.161:8848/nacos", host: "www.nacos.com:30358"
10.244.1.0 - [10.244.1.0] - - [24/Nov/2020:12:49:30 +0000] "GET /nacos HTTP/1.1" 502 565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36" 469 0.002 [default-nacos-headless-8848] [] 10.244.6.140:8848, 10.244.4.150:8848, 10.244.5.161:8848 0, 0, 0 0.001, 0.001, 0.000 502, 502, 502 0e7d8a75b16d69c90da2526855d8f88e

**Comment by fsjwin** [comment]
兄弟，你解决了吗？我也遇到这个问题了。完全按官方的搭建的。官方也不出来说个话！

**Comment by paderlol** [comment]
官方没有nginx的例子，我只是写了trafike，日志麻烦详细点，谢谢

**Comment by paderlol** [comment]
两个方面需要自查，第一是否配置正确，比如数据配置正确吗？第二配置节点的地方k8s 高版本会在域名后缀带上这个符号`.`，举个例子比如`default.cluster.`需要在配置Nacos集群节点地址的时候配置上。另外就是通常自己本地配置ingress了这个所谓的host，比如xx.com，你需要自己去改这个hosts的映射

**Comment by fsjwin** [comment]
我的问题解决了。你检查下你的nacos日志，进入nacos镜像中国看，看他是否启动成功，虽然你kubectl get po看到三个nocos都是running状态，但是nacos的日志里可能记录的是启动失败。我的失败原因是我的数据库连接失败。为什么会出现这个问题呢？因为我第一次创建数据库的时，起的数据库名字为nacos_db,创建成功后，我觉得名字起得不好，就kubectl delete -f deploy/mysql/mysql-nfs.yaml删除了，重新修改了deploy/mysql/mysql-nfs.yaml 中数据库名字为nacos_config执行也成功了。后面nacos就连接nacos_config。而事实上nacos_config并没有成功，库中仍然是nacos_db，导致nacos启动失败。
解决方案就是执行kubectl delete -f deploy/mysql/mysql-nfs.yaml，后把数据库的目录删除掉我的目录是/data/mysql，也就是你在deploy/mysql/mysql-nfs.yaml文件中nfs.path的路径（当然我配置的是/data/mysql）。然后修改并执行deploy/mysql/mysql-nfs.yaml，然后重新创建nacos，ingress(你的ingress文件很完美）我的和你的一样，哈哈，就可以正常访问了，一定要看日志哦。
（其实你从ingress日志中也能看到ingress已经收到了你的请求只是 upstream的时候决绝了，nacos就没有启动成功，当然拒绝了。看日志一定能解决问题。）

**Comment by cheungjingyu** [comment]
> 我的问题解决了。你检查下你的nacos日志，进入nacos镜像中国看，看他是否启动成功，虽然你kubectl get po看到三个nocos都是running状态，但是nacos的日志里可能记录的是启动失败。我的失败原因是我的数据库连接失败。为什么会出现这个问题呢？因为我第一次创建数据库的时，起的数据库名字为nacos_db,创建成功后，我觉得名字起得不好，就kubectl delete -f deploy/mysql/mysql-nfs.yaml删除了，重新修改了deploy/mysql/mysql-nfs.yaml 中数据库名字为nacos_config执行也成功了。后面nacos就连接nacos_config。而事实上nacos_config并没有成功，库中仍然是nacos_db，导致nacos启动失败。
> 解决方案就是执行kubectl delete -f deploy/mysql/mysql-nfs.yaml，后把数据库的目录删除掉我的目录是/data/mysql，也就是你在deploy/mysql/mysql-nfs.yaml文件中nfs.path的路径（当然我配置的是/data/mysql）。然后修改并执行deploy/mysql/mysql-nfs.yaml，然后重新创建nacos，ingress(你的ingress文件很完美）我的和你的一样，哈哈，就可以正常访问了，一定要看日志哦。
> （其实你从ingress日志中也能看到ingress已经收到了你的请求只是 upstream的时候决绝了，nacos就没有启动成功，当然拒绝了。看日志一定能解决问题。）

解决了，是nacos的问题。
