### ISSUE TITLE
创建mysql-slave-local.ymal时报错

### ISSUE THREAD

**Issue by JoeToffler** [nacos-group/nacos-k8s#18]
你好，我创建mysql-slave-local.yaml时报错
![slave](https://user-images.githubusercontent.com/31876954/54421322-2aedfa00-4747-11e9-8b5a-535776b8c826.png)

**Comment by paderlol** [comment]
你好 这是说已经创建了一个mysql id一模一样的数据库,你可以试着delete 然后重新create一下

**Comment by JoeToffler** [comment]
> 你好这是说已经创建了一个mysql id一模一样的数据库，你可以试着删除然后重新创一下

你好，删除侯重新创建依旧报相同错误，已尝试数次

**Comment by paderlol** [comment]
本地的宿主机映射的Mysql目录也删除下

**Comment by JoeToffler** [comment]
> 本地的宿主机映射的Mysql目录也删除下

好的，谢谢，根据你的提示我把slave.yaml的目录修改了一下，mysql可以正常启动
![image](https://user-images.githubusercontent.com/31876954/54501572-08cfc400-4961-11e9-882b-df5aca44cc88.png)

**Comment by paderlol** [comment]
不客气，应该的，麻烦close掉这个issue。😀
