### ISSUE TITLE
没KPI就没人写文档了嘛？

### ISSUE THREAD

**Issue by xuelangos** [nacos-group/nacos-k8s#187]
y: java.net.UnknownHostException: ${MYSQL_SERVICE_HOST}
???????????????????
没人搞就别玩开源了，恶不恶心啊

**Comment by paderlol** [comment]
我是社区的维护，并不是阿里的同学，在开源社区，请保持基本的人与人的尊重。这也是为人处世的基本道理不是吗？有问题说问题，谢谢

**Comment by paderlol** [comment]
这个文档其实可以直接参考nacos Docker的文档的，这些属性在README里面写的很清楚
