### ISSUE TITLE
Nacos 节点列表信息不一致

### ISSUE THREAD

**Issue by yangxiao1220** [nacos-group/nacos-k8s#189]
问题详细：我们在k8s 部署了nacos 1.4.0 版本中出现问题，发现三个节点的元数据存在一些问题
以下是三个节点的元数据：
nacos-0:
{
    "adWeight": "0",
    "lastRefreshTime": 1609225950404,
    "naming": {
        "ip": "nacos-0.nacos-headless.default.svc.cluster.local:8848",
        "heartbeatDueMs": 4883,
        "term": -1,
        "leaderDueMs": 7001,
        "state": "FOLLOWER"
    },
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-1.nacos-headless.default.svc.cluster.local:7848"
                ],
                "term": 49
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}

nacos-1:
{
    "adWeight": "0",
    "lastRefreshTime": 1609092812300,
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-1.nacos-headless.default.svc.cluster.local:7848"
                ],
                "term": 49
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}

nacos-2:
{
    "adWeight": "0",
    "lastRefreshTime": 1609225950166,
    "naming": {
        "ip": "nacos-2.nacos-headless.default.svc.cluster.local:8848",
        "heartbeatDueMs": 949,
        "term": -1,
        "leaderDueMs": 3013,
        "state": "FOLLOWER"
    },
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "nacos-2.nacos-headless.default.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-2.nacos-headless.default.svc.cluster.local:7848"
                ],
                "term": 46
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}

通过以上数据可以看到三个实例组成的集群出现了一些问题，leader 也出现了两个，我参考了issues 188问题，是否属同一个问题会在1.4.1 中解决。

**Comment by paderlol** [comment]
是的

**Comment by yangxiao1220** [comment]
能简述下问题么，我们当前集群如果其中有1 个nacos实例出现故障，例如pod重新调度或网络故障不可达，访问该nacos集群的客户端都会出现问题

**Comment by yangxiao1220** [comment]
谢谢大佬啦

**Comment by paderlol** [comment]
请参考 https://github.com/alibaba/nacos/issues/5346

**Comment by paderlol** [comment]
same issue #206
