### ISSUE TITLE
使用springcloud可以在k8s部署的nacos发现配置，但无法往上注册

### ISSUE THREAD

**Issue by JoeToffler** [nacos-group/nacos-k8s#19]

**Comment by paderlol** [comment]
最新版本Nacos Server 需要先去控制台新增服务，才能去启动时注册实例。

**Comment by paderlol** [comment]
1.0.0的RC版本需要

**Comment by JoeToffler** [comment]
> 1.0.0的RC版本需要

谢谢，但我试过好貌似还是不行
![image](https://user-images.githubusercontent.com/31876954/54594803-5be26d80-4a6c-11e9-978d-2de628ab414f.png)

**Comment by lking0213** [comment]
怎么可以回退到0.9.0

**Comment by paderlol** [comment]
1.客户端版本升级了吗？
2.退回版本只需要在yaml里面改变镜像版本就可以了

**Comment by bayernjava** [comment]
为啥要出这种脑残设定？自动注册有什么问题？

**Comment by paderlol** [comment]
1.0.0版本已经改了，至于手动注册是CP模式要求的，为了保证注册数据持久化，现在的默认AP模式
