### ISSUE TITLE
dns服务是kube-dns时部署nacos

### ISSUE THREAD

**Issue by KNWBIN** [nacos-group/nacos-k8s#193]
![image](https://user-images.githubusercontent.com/42708020/104900622-3e0f2800-59b7-11eb-86ca-2123b0a05ffb.png)

peer-finder   插件初始化过不去
一直出现cannot unmarshal DNS message

最后我看了下
https://github.com/kubernetes-retired/contrib/blob/master/peer-finder/peer-finder.go

_, srvRecords, err := net.LookupSRV("", "", svcName)
有一代码是这个的，SRV    

nslookup -q=srv nacos-headless         这里是我的nslookup版本太旧了

![image](https://user-images.githubusercontent.com/42708020/104901219-0bb1fa80-59b8-11eb-9823-ecff5a9e5192.png)

使用新的nslookup就是正常的
![image](https://user-images.githubusercontent.com/42708020/104977834-79533a80-5a3b-11eb-8e21-0ae195d880f9.png)

**Comment by KNWBIN** [comment]
百度查的

Go版本1.11.x中有一个补丁＃10622净额：不应压缩SRV记录中的目标域名，以加强读取SRV记录以遵循RFC-2782的方式。

如果权威DNS服务器（非兼容）使用域名压缩发送SRV记录，则 net.lookupSRV（）会引发错误，提示无法解组DNS消息（ net / lookup_unix.go＃L130 ）。例如，嵌入式Docker DNS可能会进行服务器名称压缩。

**Comment by luckyruruguo** [comment]
请问这个怎么解决呢？nslookup在哪里升级的呢？nacos的容器里没有安装nslookup命令啊
