### ISSUE TITLE
k8s环境下，nacos-server注册中心功能无法自动感知服务变化信息

### ISSUE THREAD

**Issue by niejian** [nacos-group/nacos-k8s#196]
* 镜像： **nacos-server:latest**
* 步骤：
   *  启动服务提供者（4个pod） 
   * 手动修改服务提供者实例（变为2）
    
   
     ![image](https://user-images.githubusercontent.com/7080323/107134040-74422680-6929-11eb-9193-1a87f4ab2710.png)

   * 查看nacos控制台，提供者数量没变化
   
   ![image](https://user-images.githubusercontent.com/7080323/107134083-c4b98400-6929-11eb-87c3-a8a131b41e2f.png)

**Comment by crqcheer** [comment]
正常情况，过30s就会更新实例数目的，这种问题应该不会出现。

**Comment by niejian** [comment]
> 正常情况，过30s就会更新实例数目的，这种问题应该不会出现。

我这都过去好几天了，还是一样。扩容能动态感知，删减pod后就没自动感知
