### ISSUE TITLE
集群节点注册服务不同步

### ISSUE THREAD

**Issue by hlwojiv** [nacos-group/nacos-k8s#201]
### 环境：
k8s: 1.18.8
nacos: 使用 deploy/nacos/nacos-pvc-nfs.yaml 部署
数据库和 nfs : 使用了云商的服务

### 问题描述：
在通过 K8s 的 Service 访问 nacos，我和同事所看到的服务列表不同，也会有访问不上的情况；

通过 pod 域名进一步查看后，发现 3 的节点的信息是不同步的，请问一下如何解决？

### 三节点情况截图：
nacos-0
<img width="996" alt="image" src="https://user-images.githubusercontent.com/26682806/110721430-832f3800-824b-11eb-99c0-0bc783a998d8.png">
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/26682806/110721784-26804d00-824c-11eb-897b-36e704a1caaa.png">

nacos-1
<img width="997" alt="image" src="https://user-images.githubusercontent.com/26682806/110721493-a35ef700-824b-11eb-87f3-a5962eb63e2e.png">
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/26682806/110721895-57608200-824c-11eb-82f3-78f19cb25665.png">

nacos-2
<img width="996" alt="image" src="https://user-images.githubusercontent.com/26682806/110721590-d1443b80-824b-11eb-8dc1-170546d757f8.png">
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/26682806/110721719-03ee3400-824c-11eb-96ce-3e5a4ae07ffc.png">

**Comment by paderlol** [comment]
可以看下这个issue, 现在Nacos Server端已经在排查了,你能否退回1.3.2版本看看是否还出现这个问题?
https://github.com/nacos-group/nacos-docker/issues/165#issuecomment-787618255

**Comment by paderlol** [comment]
请参考下这个Issue https://github.com/alibaba/nacos/issues/5346

**Comment by paderlol** [comment]
same issue #206
