### ISSUE TITLE
升级到1.4.1之后节点间元数据不同步

### ISSUE THREAD

**Issue by thomastttttt** [nacos-group/nacos-k8s#202]
升级到1.4.1之后，看到nacos3个节点信息如下，raftGroupMember里面全都没有nacos-0的记录，请问这样正常吗？
![image](https://user-images.githubusercontent.com/26315134/111252467-287f4d00-864c-11eb-8ec4-d06706266f7c.png)
![image](https://user-images.githubusercontent.com/26315134/111252490-359c3c00-864c-11eb-8c71-f8b899858e23.png)
![image](https://user-images.githubusercontent.com/26315134/111252514-3fbe3a80-864c-11eb-9b58-a5f906233063.png)
如果重建nacos-0的pod，会不会同步信息呢？

**Comment by onecer** [comment]
遇到一样的问题。节点之间的状态不同步。

**Comment by paderlol** [comment]
请参考 https://github.com/alibaba/nacos/issues/5346

**Comment by paderlol** [comment]
same issue #206
