### ISSUE TITLE
通过平台部署nacos集群，但是命名规则不是nacos-x这种格式，怎么配置NACOS_SERVERS

### ISSUE THREAD

**Issue by xianglong123** [nacos-group/nacos-k8s#208]
我们部署nacos用的平台，导致命名规则不是nacos-0, 名称改成了这种
![image](https://user-images.githubusercontent.com/44492803/115219323-02146c00-a13a-11eb-89d3-cbc72abb323f.png)

那我们怎么配置NACOS_SERVERS

集群就变成了这种情况
![image](https://user-images.githubusercontent.com/44492803/115219548-3a1baf00-a13a-11eb-9c11-79c3716bdb10.png)

大佬能提点意见吗？

**Comment by paderlol** [comment]
这种你就得自己配置这个节点名称

**Comment by xianglong123** [comment]
> 这种你就得自己配置这个节点名称

就是节点名称不能让他自动生成是吧，要预先指定然后配置到NACOS_SERVERS，好的，我这边尝试一下

**Comment by xianglong123** [comment]
> 这种你就得自己配置这个节点名称

就是节点名称不能让他自动生成是吧，要预先指定然后配置到NACOS_SERVERS，好的，我这边尝试一下

**Comment by xianglong123** [comment]
这个是我的问题，用的deployment部署的，改成statefulset部署就好了，3Q、
