### ISSUE TITLE
server is STARTING now, please try again later!

### ISSUE THREAD

**Issue by mnilg** [nacos-group/nacos-k8s#21]
**Scene**：

1. Nacos-K8S deployed in **Aliyun K8S cluster**
2. Use k8s **Ingress** type expose the nacos,and can access through domain
3. Get ready the config file through nacos console
4. I can get the config file through ’curl -X GET "http://cluster-ip:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test"‘，and get config file in Spring Cloud project.

**Question：**
**I can't register the service**，regadless of in Spring Cloud project alse through 'curl -X PUT 'http://cluster-ip:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'' 。And in spring cloud return **failed to req API:/nacos/v1/ns/instance after all servers([cluster-ip:8848]) tried** ,and return the result **server is STARTING now, please try again later!** through 'curl -X PUT 'http://cluster-ip:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'' .

How could I do to solve the problem?Thanks!

**Comment by paderlol** [comment]
You need to check the following nacos server logs to see if there are any exceptions

**Comment by mnilg** [comment]
> You need to check the following nacos server logs to see if there are any exceptions

How can I check the logs,I use the "**kubectl logs -f nacos-0**"，and have no any access log.Is there has any other logs?

**Comment by paderlol** [comment]
u can see the log in the nfs log or  kubectl exec in pod

**Comment by mnilg** [comment]
> u can see the log in the nfs log or kubectl exec in pod

In pod,I can see some logs in "data/" folder，where can i see the register logs!
![Uploading 057AD538-0E34-4249-8590-06D9A6C004BB.png…]()

**Comment by mawennan** [comment]
![1111](https://user-images.githubusercontent.com/4082983/56194466-a3f1b180-6065-11e9-8cec-0ce00eca604e.png)
同款问题

**Comment by mnilg** [comment]
In access_log logs，I see the error log,the status code is 503 and 400.
![05C29BAF-ED73-4fb4-B898-FD2B1E724F16](https://user-images.githubusercontent.com/7557931/56194758-33976000-6066-11e9-9509-0010b8ca0ec8.png)
![76634EDC-0D72-41c3-B978-31FAD84EEDB5](https://user-images.githubusercontent.com/7557931/56194774-3a25d780-6066-11e9-8a0f-14a00074db76.png)

Is there has any problem in nacos server config?

**Comment by mnilg** [comment]
I have 3 nodes，and exec "**tailf naming-server.log**"
![AB0D8D89-603E-40ad-8297-03A921F77705](https://user-images.githubusercontent.com/7557931/56197680-e5855b00-606b-11e9-8645-303355fffa7f.png)
![113A44EB-8278-4a2c-97F1-906F3C9ABA1F](https://user-images.githubusercontent.com/7557931/56197703-f33ae080-606b-11e9-8031-d1a4bc96f8f8.png)
![BE0516CA-0558-4b5f-8068-C07BA5CBF0E4](https://user-images.githubusercontent.com/7557931/56197714-f9c95800-606b-11e9-85e8-b936e7168e5a.png)

**Comment by mnilg** [comment]
@paderlol Tank you for your help.I solved the problem after nacos cluster restart.

**Comment by mnilg** [comment]
> ![1111](https://user-images.githubusercontent.com/4082983/56194466-a3f1b180-6065-11e9-8cec-0ce00eca604e.png)
> 同款问题
重启集群试试

**Comment by mawennan** [comment]
是的，我这边也ok。 只有重启nacos-0后才会正常，单独重启1、2都不行，所有都重启也没好使。
