### ISSUE TITLE
nacos 的服务发现和 k8s 的服务发现之间的关系?

### ISSUE THREAD

**Issue by windmeup** [nacos-group/nacos-k8s#211]
微服务部署在 k8s 上,还有必要使用 nacos 的服务发现吗?通过 k8s 发现 nacos, 再通过 nacos 发现其它服务.总感觉怪怪的.实践中如何看待这个问题?

**Comment by warthur1214** [comment]
支持k8s服务发现的微服务可以接入k8s的服务发现，nacos只保留配置中心功能。
但如果用到dubbo，还是要用nacos的服务中心的，因为dubbo目前还不支持k8s的服务发现功能。
总的来说有2种方案：
1、k8s部署nacos，使用nacos的服务中心、配置中心；
2、k8s部署nacos，使用k8s的服务中心，nacos只用配置中心；

**Comment by windmeup** [comment]
多谢!目前我也倾向于使用 k8s 的服务发现,实践中再摸索一下.

**Comment by ddbq** [comment]
使用K8S的会更好一些,因为如果使用nacos的注册中心,但应用假死或响应时间过长的情况下,应用依旧可以向nacos发送心跳.而使用k8s的探针检测机制可以通过响应时长来进行检测,可以有效做到负载均衡

**Comment by LVM-23** [comment]
> 支持k8s服务发现的微服务可以接入k8s的服务发现，nacos只保留配置中心功能。 但如果用到dubbo，还是要用nacos的服务中心的，因为dubbo目前还不支持k8s的服务发现功能。 总的来说有2种方案： 1、k8s部署nacos，使用nacos的服务中心、配置中心； 2、k8s部署nacos，使用k8s的服务中心，nacos只用配置中心；

老哥，请教一下，上面说了服务发现，说说配置相关的，K8s有configmap/secret，还需要nacos来做配置吗？configmap不支持热更新，nacos倒可以，spring-cloud-config也可以跟K8s进行热更新 ，想问问，老哥的公司怎么样用呢？取取经，谢谢
