### ISSUE TITLE
Nacos1.4.1节点异常重启后由于RAFT选举会存在持久化上个节点的IP,从而导致数据同步异常

### ISSUE THREAD

**Issue by Cassuis** [nacos-group/nacos-k8s#215]
1. Nacos 1.4.1 跑在k8s，并且持久化了 /home/nacos/data和 /home/nacos/logs
2. Naocs三节点某个节点异常重启，读取到的RAFT信息依旧是重启之前生成的RAFT信息，不知道原因必须要删除raft信息才可以正常
当前解决方案:
只有删除所有节点的/home/nacos/data/protocol 目录重新启动所有节点才可以解决

是否是我的设计或者解决方案有问题，求问有没有好的办法

**Comment by paderlol** [comment]
你可以尝试升级成1.4.2，修复了一些扩容或者意外crash的问题

**Comment by Cassuis** [comment]
> Raft信息里面应该存的是hostname吧？你是配置的hostname模式吗？

看到raft里存的的确是headless地址，理论上不会出问题，但是实际就是只要挂掉一个节点这个节点自动重启就会出现数据不一致问题。

**Comment by Cassuis** [comment]
> Raft信息里面应该存的是hostname吧？你是配置的hostname模式吗？

/home/nacos/data/protocol/raft/naming_persistent_service/snapshot/snapshot_5/__raft_snapshot_meta

 cat __raft_snapshot_meta 
jraft.LocalSnapshotPbMeta
<nacos-1.nacos-headless.pre.svc.cluster.local:7848<nacos-2.nacos-headless.pre.svc.cluster.local:7848<nacos-0.nacos-headless.pre.svc.cluster.local:7848F
naming_persistent.zip-
+{"fileMeta":{"checkSum":"4018b8c679591a1"}}

**Comment by paderlol** [comment]
应该是1.4.1的那个选举的问题，你试着用下1.4.2看看，还有如果用了peerfinder更新下镜像

**Comment by paderlol** [comment]
没有sql升级

**Comment by Cassuis** [comment]
> 没有sql升级

还有一个问题。nacos/nacos-peer-finder-plugin:1.1 这个是最新的peer-finder镜像吗.我1.4.1也是这个镜像

**Comment by Cassuis** [comment]
> 重新Pull一下吧

更新后手动干掉一个节点重启发现一个节点的元数据没有raft信息。正常吗？
{
    "lastRefreshTime": 1620640427534,
    "raftPort": "7848",
    "version": "1.4.2"
}

**Comment by paderlol** [comment]
下面那个是不正常的，选举没有成功的表现

**Comment by linux0x5c** [comment]
有结果？ 我这也有问题。重启一个节点发生了数据不一致的情况

**Comment by paderlol** [comment]
新版本应该没有这个问题了吧

**Comment by linux0x5c** [comment]
@paderlol 我2.0.3 稳定重现这个问题，集群3个节点，干掉一个节点后，向其他两个节点中任意一个节点写数据，写入成功后，启动之前被干掉的节点，查询刚才写入数据无法查到。

**Comment by linux0x5c** [comment]
![image](https://user-images.githubusercontent.com/35218713/142557683-2cb10e17-f61a-4dc0-990b-e87b9f8ddc8a.png)

{
  "servers": [
    {
      "ip": "nacos-2.nacos-headless.fat.svc.cluster.local",
      "port": 8848,
      "state": "UP",
      "extendInfo": {
        "lastRefreshTime": 1637228389310,
        "raftMetaData": {
          "metaDataMap": {
            "nacos_config": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 8
            },
            "naming_instance_metadata": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 8
            },
            "naming_persistent_service": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 9
            },
            "naming_persistent_service_v2": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 7
            },
            "naming_service_metadata": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 7
            }
          }
        },
        "raftPort": "7848",
        "version": "2.0.3"
      },
      "address": "nacos-2.nacos-headless.fat.svc.cluster.local:8848",
      "failAccessCnt": 0,
      "abilities": {
        "remoteAbility": {
          "supportRemoteConnection": true
        },
        "configAbility": {
          "supportRemoteMetrics": false
        },
        "namingAbility": {
          "supportJraft": true
        }
      }
    },
    {
      "ip": "nacos-1.nacos-headless.fat.svc.cluster.local",
      "port": 8848,
      "state": "UP",
      "extendInfo": {
        "lastRefreshTime": 1637228387921,
        "raftMetaData": {
          "metaDataMap": {
            "nacos_config": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 8
            },
            "naming_instance_metadata": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 8
            },
            "naming_persistent_service": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 9
            },
            "naming_persistent_service_v2": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 7
            },
            "naming_service_metadata": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 7
            }
          }
        },
        "raftPort": "7848",
        "version": "2.0.3"
      },
      "address": "nacos-1.nacos-headless.fat.svc.cluster.local:8848",
      "failAccessCnt": 0,
      "abilities": {
        "remoteAbility": {
          "supportRemoteConnection": true
        },
        "configAbility": {
          "supportRemoteMetrics": false
        },
        "namingAbility": {
          "supportJraft": true
        }
      }
    },
    {
      "ip": "nacos-0.nacos-headless.fat.svc.cluster.local",
      "port": 8848,
      "state": "UP",
      "extendInfo": {
        "lastRefreshTime": 1637226738333,
        "raftMetaData": {
          "metaDataMap": {
            "nacos_config": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 8
            },
            "naming_instance_metadata": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 8
            },
            "naming_persistent_service": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 9
            },
            "naming_persistent_service_v2": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 7
            },
            "naming_service_metadata": {
              "leader": "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
              "raftGroupMember": [
                "nacos-0.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-2.nacos-headless.fat.svc.cluster.local:7848",
                "nacos-1.nacos-headless.fat.svc.cluster.local:7848"
              ],
              "term": 7
            }
          }
        },
        "raftPort": "7848",
        "version": "2.0.3"
      },
      "address": "nacos-0.nacos-headless.fat.svc.cluster.local:8848",
      "failAccessCnt": 0,
      "abilities": {
        "remoteAbility": {
          "supportRemoteConnection": true
        },
        "configAbility": {
          "supportRemoteMetrics": false
        },
        "namingAbility": {
          "supportJraft": true
        }
      }
    }
  ]
}

**Comment by paderlol** [comment]
选主是成功的时候，只是查不到数据是吧

**Comment by linux0x5c** [comment]
是的 只是查不到数据

**Comment by linux0x5c** [comment]
![image](https://user-images.githubusercontent.com/35218713/142559711-7a465127-ff4f-4b0c-a671-13b0ad79d975.png)

**Comment by paderlol** [comment]
这是配置数据

**Comment by paderlol** [comment]
配置数据在数据库有吗？

**Comment by linux0x5c** [comment]
我用的是内嵌的derby数据库
