### ISSUE TITLE
为什么ceph模式下 不提供rbac用来部署，急需

### ISSUE THREAD

**Issue by carloscao0928** [nacos-group/nacos-k8s#218]

**Comment by paderlol** [comment]
https://github.com/nacos-group/nacos-k8s/blob/master/README-ceph.md K8S官方有，这并不属于nacos k8s核心点

**Comment by paderlol** [comment]
这个是由于改成subpath以后,没有修改plugins造成的,重新pull一下 已经修复了

**Comment by carloscao0928** [comment]
![微信截图_20210518153607](https://user-images.githubusercontent.com/58930323/118611331-4ce3db00-b7ef-11eb-87cd-e3fd8e044446.png)


是不是忘了写volume了 。。。写了volumeClaim
