### ISSUE TITLE
peer-finder-plugin-install CrashLoopBackOff on centos 8.2 4.18.0-193.el8.x86_64

### ISSUE THREAD

**Issue by spwangxp** [nacos-group/nacos-k8s#230]
as title showed, we deloyed perfect on centos 7.6 3.10.0-957.el7.x86_64, but when try to deploy on centos 8.2 4.18.0-193.el8.x86_64,failed, the init_container CrashLoopBackOff. the all log  we can see is "standard_init_linux.go:219: exec user process caused: exec format error"

**Comment by spwangxp** [comment]
@paderlol

**Comment by paderlol** [comment]
可能peerfinder在linux8 不兼容吧，这个只能暂时不使用，这个插件本身就是借鉴k8s官方的实验项目写的，有可能出现这种兼容问题

**Comment by spwangxp** [comment]
方便把修改后的代码放出来么？我这边尝试编译一下

**Comment by paderlol** [comment]
我记得源码在https://github.com/kubernetes-retired/contrib/blob/master/peer-finder/peer-finder.go

**Comment by spwangxp** [comment]
根据这儿看似乎您有所改动，https://github.com/nacos-group/nacos-k8s/issues/106#issuecomment-600502919
