### ISSUE TITLE
k8s部署nacos踩坑记录-集群使用PVC持久卷部署No DataSource set

### ISSUE THREAD

**Issue by master-lin** [nacos-group/nacos-k8s#239]
文件：deploy/nacos/nacos-pvc-nfs.yaml
问题：部署报错ErrMsg:Nacos Server did not start because dumpservice bean construction failure : No DataSource set
解决方法：发现yaml少了mysql地址，yaml 添加
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: mysql.host
                  name: nacos-cm

**Comment by paderlol** [comment]
嗯，感谢，方便的话可以直接提pr
