### ISSUE TITLE
nacos-pvc-nfs.yaml had a "plguindir" , may be a writting error

### ISSUE THREAD

**Issue by Warren-Z** [nacos-group/nacos-k8s#24]
As the topic.

**Comment by paderlol** [comment]
i konw that for yesterday，thanks

**Comment by nosqlcoco** [comment]
Output error log
 
`create Pod nacos-0 in StatefulSet nacos failed error: Pod "nacos-0" is invalid: [spec.containers[0].volumeMounts[0].name: Not found: "plugindir", spec.initContainers[0].volumeMounts[0].name: Not found: "plugindir"]`

**Comment by paderlol** [comment]
thanks i got it ，i will be fix it later

**Comment by paderlol** [comment]
I have fixed it.

> Output error log
> 
> `create Pod nacos-0 in StatefulSet nacos failed error: Pod "nacos-0" is invalid: [spec.containers[0].volumeMounts[0].name: Not found: "plugindir", spec.initContainers[0].volumeMounts[0].name: Not found: "plugindir"]`
