### ISSUE TITLE
operator版本是只支持1.4.1吗？

### ISSUE THREAD

**Issue by imxw** [nacos-group/nacos-k8s#270]
如题

**Comment by paderlol** [comment]
支持2.0.3

**Comment by imxw** [comment]
> 支持2.0.3

能提供一个详细的文档么，按照当前文档，感觉缺少很多细节，用的是 nacos_cluster_mysql.yaml 这个，结果数据库初始化失败，rbac到底用哪个也没有说明

controllers/Nacos "msg"="unknow error" "error"="jobs.batch \"nacos-mysql-sql-init\" is forbidden: User \"system:serviceaccount:nacos-test:nacos-operator\" cannot get resource \"jobs\" in API group \"batch\" in the namespace \"nacos-test\""

**Comment by imxw** [comment]
> > 支持2.0.3
> 
> 能提供一个详细的文档么，按照当前文档，感觉缺少很多细节，用的是 nacos_cluster_mysql.yaml 这个，结果数据库初始化失败，rbac到底用哪个也没有说明
> 
> controllers/Nacos "msg"="unknow error" "error"="jobs.batch "nacos-mysql-sql-init" is forbidden: User "system:serviceaccount:nacos-test:nacos-operator" cannot get resource "jobs" in API group "batch" in the namespace "nacos-test""

在ClusterRole中增加api group "batch" 并增加 jobs resources，该问题已解决
