### ISSUE TITLE
使用helm安装nacos集群的时候报错 is  is forbidden: User

### ISSUE THREAD

**Issue by Chaos-coder** [nacos-group/nacos-k8s#277]

**Comment by Chaos-coder** [comment]
User "xxx" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
![error](https://user-images.githubusercontent.com/35129699/147716956-b02e1b68-8198-44d5-9a58-5f00d7ef9ae3.png)

**Comment by shenkonghui** [comment]
@Chaos-coder Kubernetes版本是多少？

**Comment by shenkonghui** [comment]
@Chaos-coder 
请查看当前版本kubernetes中customresourcedefinitions的api-resources
```
> kubectl api-resources |grep CustomResourceDefinition
customresourcedefinitions               crd,crds                               apiextensions.k8s.io/v1                     false        CustomResourceDefinition
```
然后修改为对应apiVersion
https://github.com/nacos-group/nacos-k8s/blob/master/operator/chart/nacos-operator/templates/crd.yaml#L3

**Comment by shenkonghui** [comment]
@Chaos-coder 应该是你当前的kubeconfig文件配置中使用的账号没有customresourcedefinitions的权限，请使用admin权限，或者给予对应的rbac权限

**Comment by Chaos-coder** [comment]
> @Chaos-coder 应该是你当前的kubeconfig文件配置中使用的账号没有customresourcedefinitions的权限，请使用admin权限，或者给予对应的rbac权限

用的是nacos官方的项目进行的 这一块应该需要怎么配置权限呢？https://www.yuque.com/nacos/ebook/fplzfx
![image](https://user-images.githubusercontent.com/35129699/147726725-2162b600-f809-447f-95fb-6ea06c9046c9.png)

**Comment by shenkonghui** [comment]
@Chaos-coder helm工具和kubectl工具一样，采用默认kubeconfig作为访问集群的配置文件。

官方文档
https://kubernetes.io/zh/docs/concepts/configuration/organize-cluster-access-kubeconfig/

集群安装后可以在master节点的如下路径找到kubeconfig  ”/etc/kubernetes/admin.conf“。

将该文件放到本地以后，移动并且重命名为 ~/.kube/config作为默认的配置文件路径。或者通过helm install --kubeconfig指定该文件即可获得访问集群权限
