### ISSUE TITLE
每次修改完Config配置之后都需要全部重装一遍，太麻烦了

### ISSUE THREAD

**Issue by andotorg** [nacos-group/nacos-k8s#282]
但是目前发现一个方法是，可以在修改config之后，修改副本数，使其重启就生效了。

没有在修改config配置之后进行重启生效，是因为什么考虑呢？

spec:
  type: cluster
  image: nacos/nacos-server:v2.0.3
  replicas: 3
  config: |
    management.endpoints.web.exposure.include=metrics,info,httptrace,health,prometheus
    nacos.core.auth.enabled=true
 
增加一个  nacos.core.auth.enabled=true  ，没有自动重启pod，导致不生效

**Comment by paderlol** [comment]
你可以完全把application配置挂载出来,然后进行修改 像nacos.core.auth.enabled这个是会热加载的,他只会读application.properties

**Comment by andotorg** [comment]
麻烦请有什么教程可以配置下挂载到外面吗？

**Comment by paderlol** [comment]
利用configmap直接把application.properties挂载到conf目录下面就可以了,具体参考下https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume

**Comment by andotorg** [comment]
好的，谢谢

**Comment by andotorg** [comment]
但是我看了下脚本内部已经就是挂载的方式， 并且我已经修改了configmap中值之后，但是还是无法热加载
只是部分会有热加载功能对吗？ 例如  nacos.core.auth.enabled

**Comment by andotorg** [comment]
目前操作是重新clone一个nacos-client service出来，这样每次都不会动到独立的service

**Comment by paderlol** [comment]
这个问题请提到Nacos，另外cm热加载的方式本身也不推荐，时效性本身就有问题，默认是0-1分钟生效
