### ISSUE TITLE
0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.

### ISSUE THREAD

**Issue by yulongbb** [nacos-group/nacos-k8s#287]
执行quick-startup.sh脚本后nacos-0启动成功，nacos-1一直处于Pending状态

**Comment by paderlol** [comment]
这种一般都是选举不成功,或者容量不够了,可以自己用describe看下具体什么原因在pending

**Comment by 2540461056** [comment]
问题是，这个就是desc一下以后反馈的原因
