### ISSUE TITLE
Failed to pull image "nacos/nacos-peer-finder-plugin:latest"

### ISSUE THREAD

**Issue by nosqlcoco** [nacos-group/nacos-k8s#29]
Deploy nacos step by step with advanced section

```kubectl create -f nacos-k8s/deploy/nacos/nacos-pvc-nfs.yaml```

Create nacos failed,

`pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
Failed to pull image "nacos/nacos-peer-finder-plugin:latest": rpc error: code = Unknown desc = context canceled
Back-off restarting failed container`

![image](https://user-images.githubusercontent.com/3488475/56566759-03ac0780-65e6-11e9-971f-d13ddcf22ab8.png)

Nacos version: nacos/nacos-server:1.0.0
OS: Centos 7.x

**Comment by paderlol** [comment]
You might try it out by nacos/nacos-peer-finder-plugin:latest
