### ISSUE TITLE
使用helm部署集群模式时，nacos启动失败

### ISSUE THREAD

**Issue by ytqiao3** [nacos-group/nacos-k8s#307]
日志总是提示：lookup nacos-hs on 10.96.0.10:53: no such host
详情请见附件
[nacos.log](https://github.com/nacos-group/nacos-k8s/files/8338304/nacos.log)
。

**Comment by xiaohuifirst** [comment]
请问是怎么解决的？

**Comment by MohitLolo** [comment]
怎么解决的？

**Comment by MohitLolo** [comment]
健康检查那块有问题，并且.Values.nacos.health.enabled没有生效，在deployment.yaml中把探针的判断加上，{{- if .Values.nacos.health.enabled }}，然后停用探针 , enabled 设置为false
