### ISSUE TITLE
nacos-operator不再适用于k8s V1.22版本

### ISSUE THREAD

**Issue by andy-tzb** [nacos-group/nacos-k8s#309]
nacos-operator在k8s V1.22版本上，部署失败，可以考虑更新了。

> apiextensions.k8s.io/v1beta1 API 版本的 CustomResourceDefinition 不在 v1.22 版本中继续提供。
参考：[已弃用 API 的迁移指南](https://kubernetes.io/zh/docs/reference/using-api/deprecation-guide/)

**Comment by chnlcq** [comment]
@andy-tzb 我也遇到了同样的问题，请问后续你自己调整部署了么？

**Comment by rainbowechoes** [comment]
同问，官方没有修复意见吗

**Comment by shenkonghui** [comment]
@rainbowechoes 可以试试看这个[pr](https://github.com/shenkonghui/nacos-k8s/commit/3381c2a57ad3fc46e213cac990dab569393b3201)

**Comment by rainbowechoes** [comment]
> @rainbowechoes 可以试试看这个[pr](https://github.com/shenkonghui/nacos-k8s/commit/3381c2a57ad3fc46e213cac990dab569393b3201)

好的
