### ISSUE TITLE
1.0.0版本nacos访问服务列表报401错误

### ISSUE THREAD

**Issue by 77321660** [nacos-group/nacos-k8s#31]
版本：1.0.0
访问“服务列表菜单”报401错误
URL：/nacos/v1/ns/catalog/serviceList?startPg=1&pgSize=10&keyword=&namespaceId=

自动退出到登录界面

**Comment by paderlol** [comment]
你可以看下具体的server日志 或者本地启动一个看一下是否有这个问题,因为这个是权限的问题

**Comment by 77321660** [comment]
通过docker运行 nacos/nacos-server:1.0.0，访问服务列表对应的URL是：/nacos/v1/ns/catalog/`serviceList`?startPg=1&pgSize=10&keyword=&namespaceId=

而本地下载的nacos-server-1.0.0.tar.gz包解压运行，访问服务列表对应的URL是：/nacos/v1/ns/catalog/`services`?withInstances=false&pageNo=1&pageSize=10&keyword=&namespaceId=

两个URL不同，前者异常，后者正常。

**Comment by paderlol** [comment]
我知道了 应该目前的1.0.0 不是最新的包 我重新发布一次看看

**Comment by paderlol** [comment]
> 通过docker运行 nacos/nacos-server:1.0.0，访问服务列表对应的URL是：/nacos/v1/ns/catalog/`serviceList`?startPg=1&pgSize=10&keyword=&namespaceId=
> 
> 而本地下载的nacos-server-1.0.0.tar.gz包解压运行，访问服务列表对应的URL是：/nacos/v1/ns/catalog/`services`?withInstances=false&pageNo=1&pageSize=10&keyword=&namespaceId=
> 
> 两个URL不同，前者异常，后者正常。

你都是在控制台点击 还是通过api调用的?

**Comment by 77321660** [comment]
控制台点击的，发现错误时看的浏览器network访问的URL路径

**Comment by paderlol** [comment]
我刚刚确认了一下 我发布的是最新的1.0版本,并且我测试了一下,没有发现你说的问题,你看下面的截图 和你本地的url一模一样的
![image](https://user-images.githubusercontent.com/7919984/56866425-7f092100-6a0b-11e9-9026-61b18f4f9bda.png)

**Comment by paderlol** [comment]
建议清除下缓存 然后删除镜像重新pull一次看下, 因为我这边1.0.0 和 latest都确认了没有重现你这个问题。

**Comment by 77321660** [comment]
多谢，按照你的方法问题已解决。
