### ISSUE TITLE
Nacos2.0.4部署问题

### ISSUE THREAD

**Issue by zzl14273119** [nacos-group/nacos-k8s#311]
使用k8s部署nacos2.0.4版本时9848端口如何使用ingress代理出来？

**Comment by gloryxiao** [comment]
+ 1

**Comment by gloryxiao** [comment]
9848是一个grpc端口，怎么从k8s中通过 ingress代理出来？

**Comment by zzl14273119** [comment]
我们修改了Nacos在K8S中的端口暴露方式，采用了nginx做了代理，K8S集群内部可以直接访问8848和9848两个端口，外部开发时通过Nginx代理暴露

**Comment by RumbleC** [comment]
@gloryxiao 外部开发时可以通过简单端口转发将 grpc 端口暴露出来使用

 >  `kubectl port-forward service/nacos-headless 9848:9848 --address ip,localhost -n=namespace`
