### ISSUE TITLE
nacos集群 节点检查健康不正常

### ISSUE THREAD

**Issue by haoboy78** [nacos-group/nacos-k8s#320]
环境：
nacos镜像：nacos/nacos-server:1.3.2
k8s集群：1.19
nacos部署方式： kubectl apply -f nacos-quickstart.yaml

可以添加配置，在其它节点上能同步，

但是在nacos控制台中查看 集群管理->节点列表 如下：
nacos-0.nacos-headless.default.svc.cluster.local.:8848 | UP | 节点元数据
nacos-0.nacos-headless.default.svc.cluster.local:8848 | SUSPICIOUS | 节点元数据
nacos-1.nacos-headless.default.svc.cluster.local:8848 | SUSPICIOUS | 节点元数据
nacos-2.nacos-headless.default.svc.cluster.local:8848 | SUSPICIOUS | 节点元数据

这是什么问题

**Comment by hehua2018** [comment]
我也遇到这个问题，配置文件里面多了一个 nacos-0.nacos-headless.default.svc.cluster.local.:8848  nacos-0.nacos-headless.default.svc.cluster.local.

**Comment by hehua2018** [comment]
![image](https://user-images.githubusercontent.com/36179722/188425914-8cc5ec03-a1b8-4347-b38f-ae081ad4cb8e.png)
问题解决

**Comment by paderlol** [comment]
这样解决是可以,但是这个根本原因是因为K8S domain 设置尾部带了.导致的
