### ISSUE TITLE
k8s 部署 nacos2.0.3 后外部服务注册问题？

### ISSUE THREAD

**Issue by cn-core** [nacos-group/nacos-k8s#335]
@paderlol 
k8s 部署 nacos2.0.3 时 9848 端口如何使用 ingress 代理出来？
是否可以通过 ingress-nginx 暴露 9848:TCP ?
或者有什么更好的方法?

谢谢......

**Comment by opcache** [comment]
可以用ingress 代理出来，可以再创建一个NodePort svc暴露出来，哈哈哈
`apiVersion: v1
kind: Service
metadata:
  name: nacos-headless11
  namespace: test
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 30003
    - port: 9848
      name: client-rpc
      targetPort: 9848
      nodePort: 31003
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  selector:
    app: nacos`

**Comment by cn-core** [comment]
@opcache  我是在原 nacos-headless 中使用 `type: NodePort` 解决了此问题, 谢谢...

**Comment by opcache** [comment]
> nacos-headless 中使用 `type: NodePort`

nacos-headless 中使用 type: NodePort,这样就没办法自动扩缩容了吧？你那可以？peer-finder会找不到节点
