### ISSUE TITLE
如何开启权限k8s

### ISSUE THREAD

**Issue by nomatterfine** [nacos-group/nacos-k8s#341]
用这个脚本如何开启权限 
https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-no-pvc-ingress.yaml

**Comment by nomatterfine** [comment]
这样不行  
            - name: NACOS_AUTH_ENABLE
              value: true

**Comment by nomatterfine** [comment]
2.1.1

**Comment by cxhello** [comment]
> 这样不行 - name: NACOS_AUTH_ENABLE value: true

value加单引号或者双引号试试

**Comment by nomatterfine** [comment]
可以了 谢谢了
