### ISSUE TITLE
Several issues running on EKS with RDS (Missing docs, configs)

### ISSUE THREAD

**Issue by theothermike** [nacos-group/nacos-k8s#35]
I'm trying to get Nacos Server to run inside Kubernetes on the EKS Platform in AWS, in a custom Kubernetes Namespace.  The DB is a RDS instance (initially tried with no replication, then setup replication as the docs indicate a slave is needed) - so not using the nacos-mysql-server and nacos-mysql-slave images

I used nacos:nacos-server:latest (1.0.0 jar) and the latest peer-finder (matches what was defined in the k8s manifests)

Starting with the manifests in this project, I ran into several issues:

1. On startup, I saw an error from peer finder about missing $POD_NAMESPACE argument.  So that was not defined in the manifest, I defined an env var to hold this value.

2. The peer finder's plugin.sh does not add -ns argument passing $POD_NAMESPACE env var.  It is also missing the argument to define the 'nacos-headless' service name.   

Since the docker-startup.sh script does not allow manually setting the $CLUSTER_CONF file from the $NACOS_SERVER env vars if the peer-finder is mounted, I removed the 'plugin' volume mount to unblock that behaviour

3.  The configmap for Nacos does not have a value for the master host name, this causes nacos server to crash on startup.  I defined one, and then added it o the StatefulSet manifest with the required MYSQL_MASTER_SERVICE_HOST env var after finding the error on the log

4.  MYSQL_SLAVE_SERVICE_HOST is also expected, and not defined.   I created a read-replica from the master in RDS, and gave this to nacos.   

5. Nacos-server appears to attempt writing to the slave according to this error after I defined the slave host:

```2019-05-08 04:52:59,556 INFO Nacos is starting...

org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [DELETE FROM config_info WHERE data_id='com.alibaba.nacos.testMasterDB']; SQL state [HY000]; error code [1290]; The MySQL server is running with the --read-only opt
ion so it cannot execute this statement; nested exception is java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
```

Best Practices Request: Debugging this was painful.  You may consider sending start.out to STDOUT/STDERR so its easy to see what the error when using 'docker logs' or 'kubectl logs'

**Comment by theothermike** [comment]
It looks like the 5th issue, slave writing appears to have a root cause in the database not being seeded before startup.  

I manually injected the nacos-mysql.sql file from the nacos project, and then it started up as expected. 

I'll see if I can send a PR with updated docs and manifests for running in a managed Kubernetes env (EKS, GKE,AKS, etc)

**Comment by paderlol** [comment]
Sorry for the reply is too late, yes, if you need to use a custom database, you must set up the master and slave and initialize the database script. The database image I provided is my own work, but I did the documentation. There is no explanation in it, I am sorry for the inconvenience.
