### ISSUE TITLE
nacos-peer-finder-plugin容器启动完毕运行一段时间后，会一直报错

### ISSUE THREAD

**Issue by bayernjava** [nacos-group/nacos-k8s#39]
错误内容如下：
installing config scripts into /home/nacos/plugins/peer-finder
cp: cannot create regular file '/home/nacos/plugins/peer-finder/peer-finder': Text file busy

该Init Container会一直处于waiting状态，nacos容器正常，不影响使用

k8s版本：v1.13.5
docker版本：18.6.3

**Comment by paderlol** [comment]
1.13似乎peer不支持

**Comment by bayernjava** [comment]
> 1.13似乎peer不支持

能否支持一下？

**Comment by paderlol** [comment]
这个我目前也在研究更好的方式去解决这个自动扩容的方式,后续可能和DNS-F去解决,但是没有具体的落地方案

**Comment by liangyuanpeng** [comment]
@paderlol  在wiki中说明这一点我认为很重要：peer-finder当前已经不再维护，目前nacos正在积极寻找替代方案。

**Comment by paderlol** [comment]
好的

**Comment by Chaos-coder** [comment]
> @paderlol 在wiki中说明这一点我认为很重要：peer-finder当前已经不再维护，目前nacos正在积极寻找替代方案。

目前有更好的替代方案么？

**Comment by paderlol** [comment]
建议使用Nacos Operator 可以参考https://github.com/nacos-group/nacos-k8s/tree/master/operator
