### ISSUE TITLE
k8s部署后，使用ingress对外暴露服务，客户端不能正常连接

### ISSUE THREAD

**Issue by bayernjava** [nacos-group/nacos-k8s#40]
ingress配置为域名比如：nacos.examples.com 指向nacos服务的8848端口
通过网页访问nacos.examples.com/nacos可以正常打开控制台
请问springcloud的客户端yml该如何配置才能连通nacos server呢，求指教？
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS-HOST:nacos.examples.com}:${NACOS-PORT:8848}
还是：
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.examples.com

实际使用发现以上方式都不能建立连接

**Comment by paderlol** [comment]
请问报的什么错误

**Comment by bayernjava** [comment]
> 请问报的什么错误

解决了，老哥。端口需要配置，只不过配置成80就可以了，log来看不配置的话默认就是8848
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS-HOST:nacos.examples.com}:${NACOS-PORT:80}

**Comment by paderlol** [comment]
👍👍👍
