### ISSUE TITLE
[issue] nacos-operator-all.yaml format error

### ISSUE THREAD

**Issue by yjqg6666** [nacos-group/nacos-k8s#415]
Version:  master / fcf35b6ab39b5aace3dabe33a0af6916aedc2770 

$ kubectl apply -f chart/nacos-operator/nacos-operator-all.yaml

serviceaccount/nacos-operator created

**Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition**

customresourcedefinition.apiextensions.k8s.io/nacos.nacos.io created

**error: error parsing chart/nacos-operator/nacos-operator-all.yaml: error converting YAML to JSON: yaml: line 46: did not find expected '-' indicator**

$ yq -P -o json ./nacos-operator-all.yaml >/dev/null
Error: bad file './nacos-operator-all.yaml': yaml: line 1282: did not find expected '-' indicator

**Comment by wilsonwu** [comment]
Thanks for report this problem, I will try to solve it.

**Comment by FZmz** [comment]
Hey, bro, have you solved the problem yet？

**Comment by wilsonwu** [comment]
> Hey, bro, have you solved the problem yet？

Not yet, if you are interesting in it, just do it :)

**Comment by wilsonwu** [comment]
Fixed in: https://github.com/nacos-group/nacos-k8s/pull/417

Waiting for merge, but it is maybe a long time work.

**Comment by yjqg6666** [comment]
Pass by yq, no error.
