### ISSUE TITLE
关于所有yaml配置文件中环境变量NACOS_SERVERS

### ISSUE THREAD

**Issue by yangjie1993** [nacos-group/nacos-k8s#42]
当然这可能是我眼神不好，太粗心的问题 
但是我还是希望说能够在readme里面简单说一下环境变量NACOS_SERVERS的
nacos-0.nacos-headless.default.svc.cluster.local:8848，是默认在default的命名空间下才有效，如果在不同的命名空间应该修改default为正在使用的命名空间

**Comment by paderlol** [comment]
谢谢你建议,我稍后改掉

**Comment by yangjie1993** [comment]
另外 请问 一下 如何 k8s的 nacos如何 进行单机 部署呢 设置环境 变量 mode为standalone好像没有效果

**Comment by newGreenPer** [comment]
NACOS_SERVERS中的default 要和目前k8s使用的命名空间对应上
