### ISSUE TITLE
nacos-mysql这个pod的内存异常

### ISSUE THREAD

**Issue by pulsarrrr** [nacos-group/nacos-k8s#429]
k8s集群中含有操作系统为ROCKY9.2和CENTOS7的节点，使用helm部署nacos之后，nacos-mysql这个pod的内存占用在调度到ROCKY9.2的节点上很大，达到了16G，在centos主机上则只有200M左右，pod日志和strace进程都没有相关可疑的内容。

**Comment by LeeVinBin** [comment]
可以调整 containerd LimitNOFILE 或者调对应 Mysql 镜像的 ulimit
参考链接：https://github.com/containerd/containerd/issues/6707

**Comment by pulsarrrr** [comment]
Yes! it works good for me, thanks. I'll close this issue.

> 可以调整 containerd LimitNOFILE 或者调对应 Mysql 镜像的 ulimit 参考链接：[containerd/containerd#6707](https://github.com/containerd/containerd/issues/6707)
