### ISSUE TITLE
创建mysql-master-nfs.yaml 报错

### ISSUE THREAD

**Issue by a1540770111** [nacos-group/nacos-k8s#44]
![image](https://user-images.githubusercontent.com/20309960/59732879-8b2c9480-927e-11e9-90c5-11c007294fa6.png)
![image](https://user-images.githubusercontent.com/20309960/59732914-9c75a100-927e-11e9-9313-18b3dc033c8e.png)

**Comment by paderlol** [comment]
什么错误？

**Comment by a1540770111** [comment]
报的错误就是权限 docker部署的时候遇到过 需要制定权限
--privileged=true docker加这个属性  k8s 不知道

**Comment by a1540770111** [comment]
奇怪的是  运行quick-startup.sh 可以

**Comment by paderlol** [comment]
--privilege 内核参数权限，可能跟你安装docker有关系，并不是镜像导致的，然后你部署失败有看日志和describe吗？

**Comment by a1540770111** [comment]
![image](https://user-images.githubusercontent.com/20309960/59733689-5a019380-9281-11e9-8918-9437a407d56b.png)
![image](https://user-images.githubusercontent.com/20309960/59733708-64239200-9281-11e9-98e8-5b3a39957172.png)
![image](https://user-images.githubusercontent.com/20309960/59733711-67b71900-9281-11e9-96b5-743b47167107.png)
![image](https://user-images.githubusercontent.com/20309960/59733718-73a2db00-9281-11e9-9a44-4d768ccca6fe.png)

**Comment by a1540770111** [comment]
![image](https://user-images.githubusercontent.com/20309960/59733786-a77e0080-9281-11e9-8c66-49a95c12c56c.png)

**Comment by a1540770111** [comment]
![image](https://user-images.githubusercontent.com/20309960/59734685-009b6380-9285-11e9-9c7a-d464ef58de26.png)
这是刚才发现的

**Comment by paderlol** [comment]
看着都正常,我现在只能猜测原因,是否docker本身的权限问题,可以参考下这个[issue](https://github.com/docker-library/mysql/issues/187),似乎docker 安装时权限没有设置正确

**Comment by paderlol** [comment]
看着都正常,我现在只能猜测原因,
1. docker本身的权限问题,可以参考下这个[issue](https://github.com/docker-library/mysql/issues/187),似乎docker 安装时权限没有设置正确
2. NFS没有安装好,尤其是权限

**Comment by a1540770111** [comment]
好的 我自己看看  谢谢解答

**Comment by a1540770111** [comment]
谢谢耐心指导  是NFS 权限的问题
![image](https://user-images.githubusercontent.com/20309960/59735049-8e2b8300-9286-11e9-94dd-12a9b031d756.png)这么做就可以了

**Comment by paderlol** [comment]
np
