### ISSUE TITLE
启动 创建cluster.conf 文件失败

### ISSUE THREAD

**Issue by a1540770111** [nacos-group/nacos-k8s#46]
![image](https://user-images.githubusercontent.com/20309960/59910971-8d8d1b00-9445-11e9-994a-cc939f15f511.png)

**Comment by paderlol** [comment]
通过什么方式启动？nfs还是quickstart，这是代表文件没有创建成功

**Comment by a1540770111** [comment]
是nfs方式

**Comment by a1540770111** [comment]
![image](https://user-images.githubusercontent.com/20309960/59911367-4fdcc200-9446-11e9-9ccf-0d1dde45ded0.png)
这是nfd目录

**Comment by paderlol** [comment]
查看下目录是否挂载成功，然后是否有权限

**Comment by fei922** [comment]
@paderlol  请问/home/nacos/conf/cluster.conf  文件必须挂载吗，不挂载的时候会不会自动创建？之前未挂载的时候运行是可以的，现在一直报错cluster.conf  文件找不到。

**Comment by paderlol** [comment]
如果不用nfs，只用quickstart是不用挂载的

**Comment by fei922** [comment]
> 如果不用nfs，只用quickstart是不用挂载的

使用的nfs方式，可是编排文件[nacos-pvc-nfs.yaml](https://github.com/nacos-group/nacos-k8s/blob/f353fb86d8/deploy/nacos/nacos-pvc-nfs.yaml)里并没有挂载/home/nacos/conf/目录呀

**Comment by paderlol** [comment]
里面当然有挂载目录，你仔细看看

**Comment by paderlol** [comment]
说错了，cluster.conf是不会挂载目录，由脚本创建的，如果创建不成功，一般需要查看下docker本身的权限，第二个就是plguin插件没有成功

**Comment by paderlol** [comment]
我之前记错了，quickstart和nfs的cluster.conf都是脚本直接创建的，nfs是由peerfinder插件回调创建的

**Comment by fei922** [comment]
ok，谢谢。确实是自动创建了配置文件！

**Comment by a1540770111** [comment]
@fei922  你好 你的nfs的目录权限能让我看看吗

**Comment by fei922** [comment]
@a1540770111  我们nfs基本是采用的这个chart[nfs-server-provisioner](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner)部署的。
下面是其中一个挂载目录的权限，不知道是不是你想了解的。
![image](https://user-images.githubusercontent.com/9672023/60081207-ec170980-9763-11e9-8218-e6752ed79b97.png)

**Comment by a1540770111** [comment]
vim /etc/exports
这里面的权限 是什么样子

**Comment by fei922** [comment]
sh-4.3# showmount -e
Export list for nfs-server-nfs-server-provisioner-5c68b88965-wt9ct:
/export/pvc-c25ff0bc-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-f516da36-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-f5143a53-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-f517956b-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-1e9dbee8-9719-11e9-8c26-eeeeeeeeeeee (everyone)
sh-4.3# 
sh-4.3# ls /etc/exports
/etc/exports
sh-4.3# ls /etc/exports -l
-rw-r--r-- 1 root root 0 Feb 22  2016 /etc/exports
sh-4.3#

**Comment by fei922** [comment]
sh-4.3# showmount -e
Export list for nfs-server-nfs-server-provisioner-5c68b88965-wt9ct:
/export/pvc-c25ff0bc-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-f516da36-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-f5143a53-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-f517956b-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-1e9dbee8-9719-11e9-8c26-eeeeeeeeeeee (everyone)
sh-4.3#
sh-4.3# ls /etc/exports
/etc/exports
sh-4.3# ls /etc/exports -l
-rw-r--r-- 1 root root 0 Feb 22 2016 /etc/exports

**Comment by fei922** [comment]
应该就是赋了读写权限                                                                                                                                
sh-4.3# cat /export/vfs.conf                                                                            
EXPORT
{
	Export_Id = 15;
	Path = /export/pvc-1e9c26a5-9719-11e9-8c26-eeeeeeeeeeee;
	Pseudo = /export/pvc-1e9c26a5-9719-11e9-8c26-eeeeeeeeeeee;
	Access_Type = RW;
	Squash = no_root_squash;
	SecType = sys;
	Filesystem_id = 15.15;
	FSAL {
		Name = VFS;
	}
}
                                                                                                                                                               
sh-4.3# showmount -e
Export list for nfs-server-provisioner-5c68b88965-wt9ct:
/export/pvc-f5143a53-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-f517956b-9718-11e9-8c26-eeeeeeeeeeee (everyone)
/export/pvc-1e9c26a5-9719-11e9-8c26-eeeeeeeeeeee (everyone)
sh-4.3#
sh-4.3# ls /etc/exports
/etc/exports
sh-4.3# ls /etc/exports -l
-rw-r--r-- 1 root root 0 Feb 22 2016 /etc/exports
