### ISSUE TITLE
如何填写自己的数据库地址

### ISSUE THREAD

**Issue by pennpeng** [nacos-group/nacos-k8s#47]
deploy配置文件的configmap里面为啥没有mysql数据库地址的填写，我填写自己的数据库地址怎么填写。没有填写数据库地址你们是怎么来连数据库呢

**Comment by paderlol** [comment]
可以参考nacos docker 镜像配置数据库环境变量的方式

**Comment by binayabin** [comment]
具体的解决方案有吗

**Comment by skgary** [comment]
> 具体的解决方案有吗

              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848"
            - name: "PREFER_HOST_MODE"
              value: "hostname"
            - name: "MYSQL_MASTER_SERVICE_HOST"
              value: "10.23.206.1"
            - name: "MYSQL_SLAVE_SERVICE_HOST"
              value: "10.23.85.190"
