### ISSUE TITLE
nacos在kubernetes中集群模式部署，对副本数有要求吗，两个可以嘛

### ISSUE THREAD

**Issue by yunzck8s** [nacos-group/nacos-k8s#470]
在生产环境借助calico对nacos做IP固定，只能使用偶数副本数

**Comment by chuntaojun** [comment]
由于 nacos 是 ap + cp 同时运行，所以建议集群化部署采用奇数节点

**Comment by yunzck8s** [comment]
> 由于 nacos 是 ap + cp 同时运行，所以建议集群化部署采用奇数节点

请问，在kubernetes中部署，有对nacos做IP固定的方案嘛
