### ISSUE TITLE
重启pod需要删除原来的logs目录

### ISSUE THREAD

**Issue by fei922** [nacos-group/nacos-k8s#48]
![image](https://user-images.githubusercontent.com/9672023/60079950-8aee3680-9761-11e9-9b85-1b52726c0cb0.png)
有一个现象，当我删除pod重新创建的时候，查看nacos pod日志会报上面的错误。清空logs目录下的文件，启动就成功了。
nacos版本：1.0.1
k8s版本：1.13.5
使用nfs挂载的方式集群部署

**Comment by paderlol** [comment]
我这边测试没有遇到你的错误

**Comment by fei922** [comment]
好的。我这边3个pod，删除pod的时候，需要将logs目录下内容才可以，否则启动不成功。nfs存储没有用提供的编排文件，可能跟存储有关系吧。
root@master-1:/home/nacos/nacos-docker# kubectl get po -n nacos
NAME                 READY   STATUS    RESTARTS   AGE
nacos-0              1/1     Running   4          20m
nacos-1              1/1     Running   0          47m
nacos-2              1/1     Running   0          46m
