### ISSUE TITLE
k8s集群内部署，注册时报server is STARTING now

### ISSUE THREAD

**Issue by yattin** [nacos-group/nacos-k8s#54]
server is STARTING now, please try again later!

另外手工CURL访问API，也是同样的报错。

**Comment by yattin** [comment]
补充日志报错
2019-07-22 15:33:45,000 WARN [IS LEADER] no leader is available now!

**Comment by yattin** [comment]
问题更新： 3个实例启动后，需要单独重启动nacos-0后，方能正常注册。

**Comment by R1310328554** [comment]
这么奇怪的问题啊， 为啥官方没解决？

**Comment by paderlol** [comment]
日志告诉你是没有选举出leader，有可能是通讯网络，或者k8s版本等等

**Comment by paderlol** [comment]
k8s部署成功不代表你nacos选举成功

**Comment by R1310328554** [comment]
好吧， 我把 nacos-0 杀掉之后， 自动重启之后就好了。 不过， 这个真的是个坑。 我使用的是 openshift-3.11

**Comment by paderlol** [comment]
有没有具体的日志？ Nacos 0的

**Comment by lizhenghlh** [comment]
这个问题持续好久了，我在微信群和钉钉群反馈过，其他人反馈的问题都有解答，唯有这个开发人员一直忽略，应该是不好解决，所以我们现在只在测试环境使用，启动一个单独的实例

**Comment by paderlol** [comment]
…抱歉，我没有忽略我看到的问题，因为我不是全职负责这个项目，我看到问题了，我一般都尽可能的解决，我如果没有办法重现，我只能根据猜测去回答你们，所以请相互理解下，谢谢

**Comment by sohu234** [comment]
我在使用nacos:latest/1.1.3 也遇见了同样的问题 `server is STARTING now, please try again `later!。`但当我把nacos镜像版本降到1.1.0后，此问题消失。所以，估计还是nacos 1.1.3的bug

**Comment by myoss** [comment]
@paderlol 我也遇到了这个问题，`server is STARTING now, please try again later`，我降级到 1.1.0，依旧失败，能否加个好友，帮忙看看这个问题，看起来不是个例

**Comment by paderlol** [comment]
关掉健康检查试下，或者延长健康检查启动时间，readiness

**Comment by myoss** [comment]
3个容器组都是 running 状态，和这个 readiness 没有关系，去掉都没有用。感觉这个项目又太监了，都没有人解决问题。

**Comment by paderlol** [comment]
我已经回复了我的想法，也请你看下上面我的说明，请理解我不是全职，这个项目的目的更多是给大家借鉴，如果你们有时间有能力欢迎参与进来，谢谢。

**Comment by paderlol** [comment]
还有接着回答你上面的问题，running和nacos集群选举是否成功一点关系没有，请自己看一下日志是否有相关错误，还有使用哪种方式去在k8s启动的，比如快速启动或者用了nfs的方式。

**Comment by li-sen** [comment]
确实有这个 问题  1.1.4 还有这个坑

**Comment by paderlol** [comment]
@li-sen 我一直说你们把问题日志贴出来,或者问题描述的更详细一点,不然我怎么去分析问题,还有我也给出了我的猜测和分析,抱怨和提问题似乎也解决不鸟不是吗？
