### ISSUE TITLE
unable to find local peer

### ISSUE THREAD

**Issue by kengan** [nacos-group/nacos-k8s#58]
java.lang.IllegalStateException: unable to find local peer: nacos-0.nacos-headless.default.svc.cluster.local.:8848, all peers: [nacos-0.nacos-headless.default.svc.cluster.local:8848, nacos-1.nacos-headless.default.svc.cluster.local:8848, nacos-2.nacos-headless.default.svc.cluster.local:8848]

1.1.3镜像 部署在k8s 1.14上，出这个错，请问如何解决

**Comment by paderlol** [comment]
你这是hosts配置里面k8s生成的根域名，并不是nacos部署的问题，你现在用的是quickstart启动的还是？

**Comment by kengan** [comment]
quickstart启动的，我这个问题 https://github.com/nacos-group/nacos-k8s/issues/53 就是这个问题提到的  #50 ,说多了一个点，从而导致无法选举。这个日志是从pod里面的log目录下面的nacos.log  copy出来的，但是我不知道  #50  里面要怎样操作，谢谢

**Comment by paderlol** [comment]
如果你用quickstart，有两个办法解决，第一个把配置的cluster节点都加上点，还有一种写一个初始化脚本在initialContainer里面执行，把etc/hosts里面的根域名点去掉，因为这个是dns导致并不是所有的版本k8s都有这个问题

**Comment by kengan** [comment]
通过加点已经解决，谢谢
