### ISSUE TITLE
bin/docker-startup.sh: no such file or directory

### ISSUE THREAD

**Issue by innerpeacez** [nacos-group/nacos-k8s#60]
`Error: failed to start container "nacos": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"bin/docker-startup.sh\": stat bin/docker-startup.sh: no such file or directory": unknown`

请问为什么 **nacos/nacos-server:latest** 容器启动时报以上这个错误？

**Comment by paderlol** [comment]
请提供启动的方式  在什么环境？通过nfs或者别的方式启动的？最好用describle看下pod启动的错误是还是呢么

**Comment by innerpeacez** [comment]
![image](https://user-images.githubusercontent.com/37059529/63151935-38cce180-c03d-11e9-86e6-683be977f0bc.png)

pod 启动的时候就报错了，我用官方的 ceph yaml 改了一下，只是没有挂卷，其他的没有动

**Comment by paderlol** [comment]
必须要挂卷，不然你就不能使用peerfinder

**Comment by paderlol** [comment]
如果不想挂卷你就用quickstart的版本吧，本地卷那种

**Comment by innerpeacez** [comment]
![image](https://user-images.githubusercontent.com/37059529/63152509-99a8e980-c03e-11e9-97dc-39cac80e7aee.png)
![image](https://user-images.githubusercontent.com/37059529/63152519-a299bb00-c03e-11e9-8d7c-3a9542afe532.png)

我这个都改了，我只是在做一些测试，还没有需要挂卷，这样应该是可以的吧？

**Comment by innerpeacez** [comment]
![image](https://user-images.githubusercontent.com/37059529/63152509-99a8e980-c03e-11e9-97dc-39cac80e7aee.png)
![image](https://user-images.githubusercontent.com/37059529/63152519-a299bb00-c03e-11e9-8d7c-3a9542afe532.png)

我这个都改了，我只是在做一些测试，还没有需要挂卷，这样应该是可以的吧？ @paderlol

**Comment by paderlol** [comment]
不行的，这个要保证第二个容器能读到这个文件，这个init做的就是传送这个文件给nacos用

**Comment by innerpeacez** [comment]
可是我现在连第一个都没有办法启动呀 @paderlol

**Comment by paderlol** [comment]
所以你不想挂卷，就用quickstart那个就行了，那个是直接用的本地卷，只是没有peerfinder插件的功能而已

**Comment by paderlol** [comment]
你第一个已经启动了啊，你自己日志可以看到的好吗？peerfinder插件是第一个

**Comment by innerpeacez** [comment]
我这边是显示第一个POD 都没有起来，我现在把pod数改成了一个，也是没有用
![image](https://user-images.githubusercontent.com/37059529/63153168-433caa80-c040-11e9-8c86-e5973b200480.png)

**Comment by paderlol** [comment]
不是pod，是initcontainer，这个初始化容器会把peerfinder的脚本传进去，给nacos使用，你现在用的空卷，后面的nacos容器根本找不到那个脚本的

**Comment by innerpeacez** [comment]
好的，了解了，我在试试，thank you

**Comment by paderlol** [comment]
你看你截图给我的describe日志，这是一种共享卷的方式

**Comment by paderlol** [comment]
你要不挂卷可以使用提供的quickstart的方式，local的yaml

**Comment by innerpeacez** [comment]
因为后续是需要挂卷的，我就没有选择不挂卷的方式，但是忽略了initContainer 挂卷的操作的影响

**Comment by paderlol** [comment]
嗯，那我暂时先关了这个issue
