### ISSUE TITLE
NACOS-K8S官方文档案例有问题，集群连接不起来

### ISSUE THREAD

**Issue by hyj1986** [nacos-group/nacos-k8s#62]
我严格按照NACOS官方文档来进行NACOS在K8S上使用NFS自动扩容的方式来进行部署。
在最后测试是否成功的时候，报错：

server is STARTING now, please try again later!

![image](https://user-images.githubusercontent.com/3008262/63480756-a6599180-c4c5-11e9-9645-871023adfdbb.png)

**Comment by paderlol** [comment]
可以用describe看看是否nfs盘挂载成功，nfs的权限是否设置好了

**Comment by hyj1986** [comment]
> 可以用describe看看是否nfs盘挂载成功，nfs的权限是否设置好了

![image](https://user-images.githubusercontent.com/3008262/63481213-5d0a4180-c4c7-11e9-93dd-205387b5aacc.png)

这个截图里面说明应该是正常的。

另外，在NACOS主git库里面，发现有人提了关于peer-finder-plugin的issue,是否于这个相关？

**Comment by paderlol** [comment]
可以看下日志，在你的挂载卷里面或者进入pod，看看nacos-server.log或者raft.log

**Comment by hyj1986** [comment]
> 可以看下日志，在你的挂载卷里面或者进入pod，看看nacos-server.log或者raft.log

logs 文件夹里面没有nacos-server.log 我查看了一下 config-server.log
![image](https://user-images.githubusercontent.com/3008262/63481995-c12e0500-c4c9-11e9-8a92-3ecbcad57d1f.png)

naming-raft.log 里面 一直报   2019-08-22 10:44:45,000 WARN [IS LEADER] no leader is available now!

**Comment by paderlol** [comment]
把健康检查全部注释掉，readiness

**Comment by hyj1986** [comment]
> 把健康检查全部注释掉，readiness

去掉以后就好了！！！
非常感谢！！

![image](https://user-images.githubusercontent.com/3008262/63482365-3948fa80-c4cb-11e9-8a0d-b76d092c401d.png)

两个总结：
1. 能否把官方文档修改一下，我一开始是使用的RDS数据库，然后尝试修改各种配置。折腾了2天。曾经一度正常过，然后就不正常了。
严格按照官方文档来做，结果还是有问题。那么只能说是官方文档不严谨。
2. 文档里有一个命令
`kubectl exec nacos-$i curl GET "http://localhost:8848/nacos/v1/ns/raft/state"; done`
我这边执行是报错的， 取消 "GET"就可以了，烦请验证一下。如果真是有问题，麻烦也更新一下文档。谢谢！

**Comment by paderlol** [comment]
好的😊，那可以关闭这个issue，把文档问题再次提一个新issue。
