### ISSUE TITLE
k8s nacos nfs  ：cannot get serverlist, so exit.

### ISSUE THREAD

**Issue by kiddlovemoon** [nacos-group/nacos-k8s#68]
k8s v1.15.3
nacos.log
 Error creating bean with name 'serverListService': Invocation of init method failed; nested exception is java.lang.RuntimeException: cannot get serverlist, so exit.
config-server.log
2019-09-25 09:26:13,091 INFO ADDRESS_SERVER_URL:http://jmenv.tbsite.net:8080/nacos/serverlist

2019-09-25 09:26:13,093 ERROR nacos-XXXX

java.io.FileNotFoundException: /home/nacos/conf/cluster.conf (No such file or directory)

**Comment by paderlol** [comment]
这是没启动成功，这个可能是nfs权限造成的…不能创建文件

**Comment by kiddlovemoon** [comment]
本地/data/nfs-share/下都已经成功写入。

**Comment by wuyue92tree** [comment]
遇到了同样的问题，有解决方案么 @kiddlovemoon

**Comment by paderlol** [comment]
本地写入成功了吗？本地写入成功那么就应该能读取到，你上面那个错误大概率就是权限导致的读不到或者写入问题，你要看下你nfs这边配置的权限。

**Comment by wuyue92tree** [comment]
cluster.conf 这个配置文件是 通过
`./peer-finder -on-start=/home/nacos/plugins/peer-finder/on-start.sh -on-change=/home/nacos/plugins/peer-finder/on-change.sh -service=nacos-headless`
这个命令生成的吧？容器的 /home/nacos/conf  这个目录不是通过nfs挂载的，应该创建cluster.conf这个配置文件和nfs无关吧

我试着在容器单独跑了下
`./peer-finder -on-start=/home/nacos/plugins/peer-finder/on-start.sh -on-change=/home/nacos/plugins/peer-finder/on-change.sh -service=nacos-headless` 这个命令直到容器异常退出，都没有任何输出

**Comment by wuyue92tree** [comment]
经查证，在`plugins.sh`中，通过shell操作hosts文件以监听nacos节点，但脚本中将集群域名写死了，
```
#!/usr/bin/env bash
PEER_FINDER_DIR="/home/nacos/plugins/peer-finder"
cp /etc/hosts ~/hosts.new && sed -i 's/cluster.local.[][]*/cluster.local /g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts
cd ${PEER_FINDER_DIR}
./peer-finder -on-start=${PEER_FINDER_DIR}/on-start.sh -on-change=${PEER_FINDER_DIR}/on-change.sh -service=${SERVICE_NAME} &
```
若集群域名不为`cluster.local`，将监听不到nacos任意节点，导致一直失败。

这也是为什么`./peer-finder -on-start=/home/nacos/plugins/peer-finder/on-start.sh -on-change=/home/nacos/plugins/peer-finder/on-change.sh -service=nacos-headless`该命令为什么没有任何输出的原因❤️

我因为在创建集群时对集群域名进行了自定义，所以一直异常退出。修改回`cluster.local`或者自定义peer-finder镜像即可。

**Comment by paderlol** [comment]
谢谢,我对插件镜像优化了下,应该修复你这个问题了,可以看一下[使用peerfinder扩容插件](https://github.com/nacos-group/nacos-k8s/wiki/%E4%BD%BF%E7%94%A8peerfinder%E6%89%A9%E5%AE%B9%E6%8F%92%E4%BB%B6)d的Wiki
