### ISSUE TITLE
NFS 服务的作用？

### ISSUE THREAD

**Issue by fudali113** [nacos-group/nacos-k8s#7]
如果我把 mysql 部署在 k8s 集群外部，那我还需要 NFS 服务么？

**Comment by fudali113** [comment]
> NFS是为了容器数据持久化，nacos下面的data，以及节点信息，都会需要持久化。mysql不使用也可以的，只是需要自己做数据持久化。

nacos 里面的 data 主要会包含些什么数据啊？ 节点信息貌似只需要配置 ip:port 就可以了哒？

@paderlol

**Comment by paderlol** [comment]
data里面是节点之间的交互数据，以及心跳包和注册信息。

**Comment by fudali113** [comment]
> data里面是节点之间的交互数据，以及心跳包和注册信息。

如果我只想使用 nacos-config ， 去掉 NFS 有没有什么影响？ @paderlol

**Comment by paderlol** [comment]
不过你不用nfs的话，你就直接用quick start的部署就好了，不过nacos自动扩容插件是一定需要用到类似nfs这种pvc持久化服务的，所以具体要权衡一下，还有如果是上生产还是考虑下使用持久卷

**Comment by nosqlcoco** [comment]
> 如果配置在集群外部，要注意配置MYSQL_MASTER_HOST和MYSQL_SLAVE_HOST，因为你在k8s外部，所以地址信息得自己配置

请把 `MYSQL_MASTER_HOST` 和 `MYSQL_SLAVE_HOST` 加到 `nacos-pvc-nfs.yaml`  里面

**Comment by tigerba** [comment]
nacos 部署在k8s集群上，部署方式没有使用stateful方式，而是使用了deployment方式部署（3份），并通过ingress 暴露服务后，访问ingress后会出现多次请求数据不一致情况。是因为没有使用pvc的原因吗？
