### ISSUE TITLE
k8s环境中注册显示OK，但是没有读取成功

### ISSUE THREAD

**Issue by rongyi** [nacos-group/nacos-k8s#72]
k8s version:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

搭建方式：
nfs方式搭建
POD状态：
mysql-master-9hfsp                        1/1     Running   0          39m  
mysql-slave-jsp2g                         1/1     Running   0          38m  
nacos-0                                   1/1     Running   0          15m 
nacos-1                                   1/1     Running   0          13m   
nacos-2                                   1/1     Running   0          12m  

服务注册：

```
http -v PUT 'http://nacos-headless:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
PUT /nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: nacos-headless:8848
User-Agent: HTTPie/0.9.8



HTTP/1.1 200 
Content-Length: 2
Date: Thu, 24 Oct 2019 12:02:55 GMT

ok
```

读取
```
http -v  GET 'http://nacos-headless:8848/nacos/v1/ns/instances?serviceName=nacos.naming.serviceName'
GET /nacos/v1/ns/instances?serviceName=nacos.naming.serviceName HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: nacos-headless:8848
User-Agent: HTTPie/0.9.8



HTTP/1.1 401 
Content-Length: 0
Date: Thu, 24 Oct 2019 12:04:19 GMT


```

但是config可以成功写入和读取
测试如下：

```
http -v POST "http://nacos-headless:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=helloWorld"                                                                              
POST /nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=helloWorld HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: nacos-headless:8848
User-Agent: HTTPie/0.9.8



HTTP/1.1 200 
Content-Type: application/json;charset=UTF-8
Date: Thu, 24 Oct 2019 12:05:45 GMT
Transfer-Encoding: chunked

true
```

```
http -v  GET "http://nacos-headless:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test"
GET /nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: nacos-headless:8848
User-Agent: HTTPie/0.9.8



HTTP/1.1 200 
Cache-Control: no-cache,no-store
Content-Length: 10
Content-MD5: 1a833da63a6b7e20098dae06d06602e1
Content-Type: application/json;charset=UTF-8
Date: Thu, 24 Oct 2019 12:06:49 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Thu, 24 Oct 2019 11:57:36 GMT
Pragma: no-cache

helloWorld

```

很奇怪，求指导

**Comment by paderlol** [comment]
这是注册中心leader没选举成功，注释掉readiness这些探测，可能由于探测引起的

**Comment by rongyi** [comment]
@paderlol 多谢回复， 刚刚测试了一下注释掉nacos-nfs.yaml如下部分：

```
         # readinessProbe:
         #   httpGet:
         #     port: client-port
         #     path: /nacos/v1/console/health/readiness
         #   initialDelaySeconds: 60
         #   timeoutSeconds: 3
```
 测试发现还是一样，后面把livenessProbe也注释掉了，结果还是一样。
naming-server.log的日志有些
`
2019-10-25 10:21:03,716 WARN cluster: DEFAULT not found, ip: {"app":"DEFAULT","clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"instanceId":"20.18.7.10#8080#DEFAULT#DEFAULT_GROUP@@nacos.naming.serviceName","ip":"20.18.7.10","ipDeleteTimeout":30000,"lastBeat":1571970063493,"marked":false,"metadata":{},"port":8080,"serviceName":"DEFAULT_GROUP@@nacos.naming.serviceName","tenant":"","weight":1.0}, will create new cluster with default configuration.`


```
2019-10-25 10:21:21,278 INFO receive config info: unknown#nacos-2.nacos-headless.default.svc.cluster.local:8848#1571970081275#1

2019-10-25 10:21:24,001 INFO receive config info: unknown#nacos-1.nacos-headless.default.svc.cluster.local:8848#1571970083998#1

2019-10-25 10:21:28,763 INFO receive config info: unknown#nacos-0.nacos-headless.default.svc.cluster.local:8848#1571970088763#1

```
