### ISSUE TITLE
/home/nacos/conf/cluster.conf找不到

### ISSUE THREAD

**Issue by wayilau** [nacos-group/nacos-k8s#74]
Cann't not find the cluster.conf when i use glusterfs instead of nfs to boot nacos on k8s env.
All the pv created. 
here the mounts:
  
![image](https://user-images.githubusercontent.com/3197838/68197749-b6c5d680-fff5-11e9-937c-6252e5c00c8d.png)
Any one can help me ?

**Comment by paderlol** [comment]
I think you may need to check the read and write permissions of the config directory.

**Comment by wayilau** [comment]
How could i do this?

**Comment by paderlol** [comment]
I think you can take a look at glusterfs authorization Settings for directories, I don't know much about glusterfs, sorry

**Comment by wayilau** [comment]
@paderlol It is relate with gfs? when i run plugin.sh in container, it also can not create the cluster.conf file.

**Comment by paderlol** [comment]
Yep.Because this has happened before with NFS

**Comment by wayilau** [comment]
Could i add a share folder /home/nacos/conf using volumes type of emptyDir to resove this ?

**Comment by paderlol** [comment]
U can try. I think it might work out

**Comment by wayilau** [comment]
i have tried, it doesn't work.at last i remove the init container, i use env NACOS_SERVERS instead.
i will add value manually.
