### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by huohuanhuan** [nacos-group/nacos-k8s#75]
cp /etc/hosts ~/hosts.new && sed -i 's/cluster.local. /cluster.local /g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts

2个空格导致的BUG。
修改为下面即可恢复
cp /etc/hosts ~/hosts.new && sed -i 's/cluster.local./cluster.local/g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts

**Comment by paderlol** [comment]
I got it thanks

**Comment by huohuanhuan** [comment]
you welcome

**Comment by baobeidaodao** [comment]
@paderlol 此 bug 修复之后，docker 镜像是不是也要更新一下？

**Comment by paderlol** [comment]
这个不是bug修复…而是要考虑兼容有点和没点，这个如果修复了，没点执行这个脚本会有问题。

**Comment by paderlol** [comment]
还有点后面空格不固定的问题

**Comment by paderlol** [comment]
已经提交一个修复了,你可以看下,我这边测试了下没问题.@huohuanhuan

@huohuanhuan 

@baobeidaodao 这个不需要更新docker镜像 这个只是peer-finder这个插件的issue

**Comment by baobeidaodao** [comment]
@paderlol 你好，我理解的是：这个 peer-finder 是一个插件，所以不需要更新 nacos/nacos-server 的镜像。那么需要把 nacos/nacos-peer-finder-plugin 这个镜像更新一下吗？？

**Comment by paderlol** [comment]
有更新的
