### ISSUE TITLE
集群一直在不停的选举中

### ISSUE THREAD

**Issue by jzbbobo** [nacos-group/nacos-k8s#78]

**Comment by paderlol** [comment]
注释掉readiness相关检查的配置

**Comment by jzbbobo** [comment]
@paderlol 用的是 nacos-quick-start.yaml 创建的呢，没有配置 readiness检查

**Comment by paderlol** [comment]
我知道了,应该是你用的quickstart的例子,这个是没用任何卷的,所以会出现不停重新选举,因为选举数据每次都写的是临时文件

**Comment by paderlol** [comment]
我知道了,应该是你用的quickstart的例子,这个是没用任何卷的,所以会出现不停重新选举,因为选举数据每次都写的是临时文件

**Comment by jzbbobo** [comment]
@paderlol 好的 那么可以显式配置这个选举数据写文件的位置不？或者是我挂一个pvc到这里
