### ISSUE TITLE
客户端的配置缓存未更新？

### ISSUE THREAD

**Issue by level077** [nacos-group/nacos-k8s#79]
有两组nacos集群，一个在k8s，一个在常规的虚拟机中，后端的mysql都是同一个。
当前遇到个问题，通过nacos（随意一组nacos）修改配置后，k8s中的客户端读到了新配置，虚拟机中的客户端的本地存放的配置文件也更新了，但是从程序中的日志看到配置还是旧的，重起业务也不行，直到echo 1 > /proc/sys/vm/drop_caches，才读到了新的配置，这大概是什么问题？是因为pagecache中的内容没有更新掉？

**Comment by paderlol** [comment]
听你的描述似乎是客户端的缓存问题，并不是服务端未推送吧？

**Comment by level077** [comment]
是的，看着应该是客户端缓存问题。对nacos不是很了解，所以询问下大概什么原因，之前一直没遇到过。

**Comment by paderlol** [comment]
那你应该把这个问题提交到nacos的issue里面，描述下具体使用的nacos版本，客户端数据有没有收到推送，是没推送也没有写文件还是推送了没写文件

**Comment by level077** [comment]
好的
