### ISSUE TITLE
nacos on k8s但mysql部署在k8s集群之外的情况。

### ISSUE THREAD

**Issue by slieer** [nacos-group/nacos-k8s#81]
请教一下nacos上k8s， 如果已经有mysql 服务是部署在k8s集群之外的。 这种情况下nacos-pvc-nfs.yaml 如果修改？  

还有目前是否支持？

**Comment by paderlol** [comment]
可以，你可以用自己的数据库，配置方式和使用docker镜像配置方式一样

**Comment by slieer** [comment]
nacos-pvc-nfs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.master.db.name: "nacos_config"
  mysql.master.port: "3306"
  mysql.slave.port: "3306"
  mysql.master.user: "nacos"
  mysql.master.password: "nacos"
---

能在这里指定mysql服务的地址信息吗？   文档和yaml中只有上面的数据库属性，没有msql 服务地址字段啊。 怎么办？

**Comment by paderlol** [comment]
请参考nacos docker镜像的readme文档

**Comment by slieer** [comment]
https://github.com/nacos-group/nacos-docker/blob/master/README.md
Common property configuration
有这两个
`

**MYSQL_MASTER_SERVICE_HOST** | mysql master host |  
-- | -- | --
MYSQL_MASTER_SERVICE_PORT | mysql master database port | default : 3306
MYSQL_MASTER_SERVICE_DB_NAME | mysql master database name |  
MYSQL_MASTER_SERVICE_USER | username of master database |  
MYSQL_MASTER_SERVICE_PASSWORD | password of master database |  
**MYSQL_SLAVE_SERVICE_HOST** | mysql slave host |  
MYSQL_SLAVE_SERVICE_PORT | mysql slave database port | default :3306
MYSQL_DATABASE_NUM | It indicates the number of database | default :2

`

对应到nacos-pvc-nfs.yaml中，是不是：
mysql.master.service.host
mysql.slave.service.host
这两个属性？

**Comment by slieer** [comment]
see my yaml:
https://github.com/slieer/nacos-k8s/tree/master/nacos-k8s-mysql-nfs

**Comment by slieer** [comment]
This problem is resolved.

**Comment by MQPearth** [comment]
> see my yaml: https://github.com/slieer/nacos-k8s/tree/master/nacos-k8s-mysql-nfs

nacos的人多少得给你磕一个
