### ISSUE TITLE
helm chart的mysql slave写法有问题

### ISSUE THREAD

**Issue by wangshiyang** [nacos-group/nacos-k8s#86]
mysql/templates/slave-pvc.yaml
中的
`{{- if ne .Values.global.mode "quickstart" }}
{{- if and .Values.slave.persistence.enabled (not .Values.slave.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.slave.persistence.claim.name }}
spec:
  {{ toYaml .Values.**master**.persistence.claim.spec | indent 2 }} 
{{- end }}
{{- end }}
`
应该是:
.Values.**slave**.persistence.claim.spec

**Comment by paderlol** [comment]
好的,你能提一个pr上来吗

**Comment by paderlol** [comment]
谢谢,我已经修复了
