### ISSUE TITLE
mysal-nfs 部署，出现nfs文件锁问题/

### ISSUE THREAD

**Issue by wjlzk1** [nacos-group/nacos-k8s#89]
mysql的master和slave在使用nfs 挂载时，slave在master成功部署后，会出现报错日志。
InnoDB: Unable to lock ./ibdata1 error: 11
InnoDB: Check that you do not already have another mysqld process using the same InnoDB data or log files.

**Comment by paderlol** [comment]
看错误似乎master和slave挂到一个卷里面去了
