### ISSUE TITLE
Kubernetes 安装与配置能否提供下代码

### ISSUE THREAD

**Issue by 13539956066** [nacos-group/nacos-k8s#9]
Centos 7.4
yum install -y kubernetes  docker flannel docker-compse 
我的 kubernetes 可能是配置不对。
cd nacos-k8s
[root@VM_0_9_centos nacos-k8s]# kubectl create -f deploy/nfs/rbac.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by paderlol** [comment]
在Nacos 0.9 或者 1.0版本的时候我会整理好相关详细文档出来,包括k8s安装
