### ISSUE TITLE
执行kubectl create -f nacos-pvc-nfs.yaml不成功

### ISSUE THREAD

**Issue by AjaxMa** [nacos-group/nacos-k8s#91]
执行后在dashboard界面查看pod报错：error while running "VolumeBinding" filter plugin for pod "nacos-0": pod has unbound immediate PersistentVolumeClaims
请问这个要怎么修复？

**Comment by paderlol** [comment]
describe 下你的服务 看看挂卷哪里出问题了,还有描述下你使用的k8s哪个方式进行部署的
