### ISSUE TITLE
Could not resolve placeholder 'MYSQL_SERVICE_HOST'

### ISSUE THREAD

**Issue by pansx** [nacos-group/nacos-k8s#93]
![TIM截图20200220101026](https://user-images.githubusercontent.com/6763939/74894231-55215080-53c9-11ea-8222-fb269a7d14bd.png)
java.io.IOException: java.lang.IllegalArgumentException: Could not resolve placeholder 'MYSQL_SERVICE_HOST' in value "jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true"

版本:{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

mysql主从使用nfs部署成功查看log无错误,部署nacos不停重启,start.out出现上面的错误

**Comment by paderlol** [comment]
最新已经移除mysql主从，具体原因请查看nacos docker README

**Comment by pansx** [comment]
java.io.IOException: java.lang.IllegalArgumentException: Could not resolve placeholder 'MYSQL_SERVICE_HOST' in value "jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true"

删除从数据库后错误依旧

**Comment by paderlol** [comment]
数据库要重新部署啊，数据库部署文件也更新了

**Comment by pansx** [comment]
谢谢,问题解决
