### ISSUE TITLE
helm lint Error，

### ISSUE THREAD

**Issue by rim-wood** [nacos-group/nacos-k8s#98]
helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "nacos/charts/mysql/templates/storageclass.yaml": template: nacos/charts/mysql/templates/storageclass.yaml:1:18: executing "nacos/charts/mysql/templates/storageclass.yaml" at <.Values.mysql.persistence.enabled>: nil pointer evaluating interface {}.persistence

**Comment by dlhf** [comment]
看了下，貌似还没搞全

**Comment by paderlol** [comment]
不是没搞全，是所有的value在nacos的vaules.yaml里面，需要单独启动mysql自取

**Comment by rim-wood** [comment]
> 不是没搞全，是所有的value在nacos的vaules.yaml里面，需要单独启动mysql自取

是的，是因为charts中mysql文件夹下的vaules.yaml文件里面没有值，需要从外面的vaules.yaml中把mysql的值放到里面去
