### ISSUE TITLE
create nacos-pvc-nfs.yaml后只有一个nacos-0，而且一直在init状态

### ISSUE THREAD

**Issue by songmz** [nacos-group/nacos-k8s#99]

**Comment by songmz** [comment]
kubectl create -f deploy/nacos/nacos-pvc-nfs.yaml
service/nacos-headless created
configmap/nacos-cm created
statefulset.apps/nacos created


查看pod
kubectl get pod -o wide
NAME                                     READY   STATUS     RESTARTS   AGE     IP               NODE               NOMINATED NODE   READINESS GATES
mysql-zqzwm                              1/1     Running    0          7m49s   192.168.129.75   kubernetes-node1   <none>           <none>
nacos-0                                  0/1     Init:0/1   0          11s     <none>           kubernetes-node3   <none>           <none>
nfs-client-provisioner-bcc5b887c-26vwx   1/1     Running    0          11m     192.168.129.74   kubernetes-node1   <none>           <none>

**Comment by paderlol** [comment]
请自己用describe 排查下原因，通常都是peerfinder没启动成功导致，要么nfs没法创建文件。

**Comment by songmz** [comment]
nfs可以正常创建文件
`root@ubuntu:/data/nfs-share# ll
total 20
drwxrwxrwx 5 root root 4096 Mar  1 13:47 ./
drwxr-xr-x 6 root root 4096 Mar  1 10:30 ../
drwxrwxrwx 2 root root 4096 Mar  1 13:47 default-datadir-nacos-0-pvc-eca1e752-117a-4e1f-8cc0-aa2e8d19625d/
drwxrwxrwx 2 root root 4096 Mar  1 13:47 default-logdir-nacos-0-pvc-19482689-79ae-4a6a-85c3-752768f27623/
drwxrwxrwx 2 root root 4096 Mar  1 13:47 default-plugindir-nacos-0-pvc-f189dfd1-6674-480a-8d23-baf9002943de/
`
mysql也可以正常连接，
kubectl describe svc nacos-headless 也没看出什么问题啊

3个node上的image: nacos/nacos-peer-finder-plugin:1.0和image: nacos/nacos-server:latest也没pull下来，我就手动pull了一下，然后把imagePullPolicy改为IfNotPresent，结果还是一址在init

**Comment by paderlol** [comment]
kubectl describe pod nacos-0

**Comment by paderlol** [comment]
参考下这个wiki https://github.com/nacos-group/nacos-k8s/wiki/%E4%BD%BF%E7%94%A8peerfinder%E6%89%A9%E5%AE%B9%E6%8F%92%E4%BB%B6

**Comment by songmz** [comment]
describe看了一下，mount时有问题，网上搜了一圈也不知道该如何解决啊

部分报错的信息
`  Warning  FailedScheduling  <unknown>  default-scheduler          error while running "VolumeBinding" filter plugin for pod "nacos-0": pod has unbound immediate PersistentVolumeClaims`

`  Warning  FailedMount       28m        kubelet, kubernetes-node3  MountVolume.SetUp failed for volume "pvc-f189dfd1-6674-480a-8d23-baf9002943de" : mount failed: exit status 32`

`mount: /var/lib/kubelet/pods/8a9e554a-c8f8-4698-9410-bcebaa47ca8a/volumes/kubernetes.io~nfs/pvc-f189dfd1-6674-480a-8d23-baf9002943de: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.`

**Comment by paderlol** [comment]
你是用的本地搭建的？

**Comment by songmz** [comment]
在vmware中搭建的，一台master, 3台node，一台volume

`kubectl version

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by paderlol** [comment]
这似乎不是nacos 和 k8s的问题,我看着像nfs的问题

**Comment by paderlol** [comment]
你nfs装全了吗？

**Comment by paderlol** [comment]
你看下你是不是因为这个问题导致的https://askubuntu.com/questions/525243/why-do-i-get-wrong-fs-type-bad-option-bad-superblock-error

**Comment by songmz** [comment]
那台volume上安装了
`apt-get install -y nfs-kernel-server`
`apt-get install -y nfs-common`
`apt-get install -y cifs-utils`

但没搞懂报错信息的意思是说在nfs-client-provisioner中无法执行mount，还是在nacos-0中无法执行mount啊

**Comment by songmz** [comment]
贴出一段完整的信息，里面有说执行systemd-run命令，不确定是指在哪个pod容器中执行的systemd-run，反正nfs-client-provisioner  pod中没有这个命令

`  Warning  FailedScheduling  <unknown>  default-scheduler          error while running "VolumeBinding" filter plugin for pod "nacos-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         <unknown>  default-scheduler          Successfully assigned default/nacos-0 to kubernetes-node3
  Warning  FailedMount       28m        kubelet, kubernetes-node3  MountVolume.SetUp failed for volume "pvc-f189dfd1-6674-480a-8d23-baf9002943de" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/8a9e554a-c8f8-4698-9410-bcebaa47ca8a/volumes/kubernetes.io~nfs/pvc-f189dfd1-6674-480a-8d23-baf9002943de --scope -- mount -t nfs 192.168.180.35:/data/nfs-share/default-plugindir-nacos-0-pvc-f189dfd1-6674-480a-8d23-baf9002943de /var/lib/kubelet/pods/8a9e554a-c8f8-4698-9410-bcebaa47ca8a/volumes/kubernetes.io~nfs/pvc-f189dfd1-6674-480a-8d23-baf9002943de
Output: Running scope as unit: run-r7ca3e0f7c5764f0c81053d27c726cffa.scope
mount: /var/lib/kubelet/pods/8a9e554a-c8f8-4698-9410-bcebaa47ca8a/volumes/kubernetes.io~nfs/pvc-f189dfd1-6674-480a-8d23-baf9002943de: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.`

**Comment by paderlol** [comment]
kubernetes-node3 你这个节点上面装了吗？

**Comment by paderlol** [comment]
这就是nfs没搞好 我没搞过用虚拟机去搭建,我真实的云机验证没出这个问题

**Comment by paderlol** [comment]
还有所有的k8s node节点需要安装nfs的客户端

**Comment by songmz** [comment]
分别在3台node上都安装了一下
`apt-get -y install nfs-common`
`apt-get -y  install cifs-utils`

现在两台nacos都启动成功了

哎。。。没想到是要在node节点上直接安装nfs客户端，还以为是在pod的容器中安装的来着

多谢啦兄弟！！！

**Comment by paderlol** [comment]
不客气 共同讨论

**Comment by paderlol** [comment]
如果issue已经解决了,就close一下哈
